package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnnotationsLog generated by hbm2java
 */
@Entity
@Table(name = "annotations_log")
public class AnnotationsLog implements java.io.Serializable {

	private long id;
	private Annotations annotations;
	private Processes processes;
	private Publications publications;
	private Corpus corpus;
	private String annotLogType;
	private String annotOld;
	private String annotNew;
	private String notes;
	private Date annotLogDate;

	public AnnotationsLog() {
	}

	public AnnotationsLog(long id, Processes processes, Publications publications, Corpus corpus, String annotLogType, String annotOld, String annotNew, Date annotLogDate) {
		this.id = id;
		this.processes = processes;
		this.publications = publications;
		this.corpus = corpus;
		this.annotLogType = annotLogType;
		this.annotOld = annotOld;
		this.annotNew = annotNew;
		this.annotLogDate = annotLogDate;
	}

	public AnnotationsLog(long id, Annotations annotations, Processes processes, Publications publications, Corpus corpus, String annotLogType, String annotOld, String annotNew, String notes, Date annotLogDate) {
		this.id = id;
		this.annotations = annotations;
		this.processes = processes;
		this.publications = publications;
		this.corpus = corpus;
		this.annotLogType = annotLogType;
		this.annotOld = annotOld;
		this.annotNew = annotNew;
		this.notes = notes;
		this.annotLogDate = annotLogDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annotations_id")
	public Annotations getAnnotations() {
		return this.annotations;
	}

	public void setAnnotations(Annotations annotations) {
		this.annotations = annotations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processes_id", nullable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publications_id", nullable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corpus_id", nullable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@Column(name = "annot_log_type", nullable = false, length = 14)
	public String getAnnotLogType() {
		return this.annotLogType;
	}

	public void setAnnotLogType(String annotLogType) {
		this.annotLogType = annotLogType;
	}

	@Column(name = "annot_old", nullable = false, length = 300)
	public String getAnnotOld() {
		return this.annotOld;
	}

	public void setAnnotOld(String annotOld) {
		this.annotOld = annotOld;
	}

	@Column(name = "annot_new", nullable = false, length = 300)
	public String getAnnotNew() {
		return this.annotNew;
	}

	public void setAnnotNew(String annotNew) {
		this.annotNew = annotNew;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "annot_log_date", nullable = false, length = 19)
	public Date getAnnotLogDate() {
		return this.annotLogDate;
	}

	public void setAnnotLogDate(Date annotLogDate) {
		this.annotLogDate = annotLogDate;
	}

}
