package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Annotations generated by hbm2java
 */
@Entity
@Table(name = "annotations")
public class Annotations implements java.io.Serializable {

	private long id;
	private ResourceElements resourceElements;
	private Processes processes;
	private Classes classes;
	private Publications publications;
	private Corpus corpus;
	private long annotStart;
	private long annotEnd;
	private String element;
	private String normalizationForm;
	private String annotType;
	private String clue;
	private String classificationRe;
	private boolean active;
	private Long startSentenceOffset;
	private Long endSentenceOffset;
	private String notes;
	private Set<AnnotationsProperties> annotationsPropertieses = new HashSet<AnnotationsProperties>(0);
	private Set<AnnotationsSide> annotationsSidesForIdannotationsSubId = new HashSet<AnnotationsSide>(0);
	private Set<AnnotationsLog> annotationsLogs = new HashSet<AnnotationsLog>(0);
	private Set<AnnotationsSide> annotationsSidesForAnnotationsId = new HashSet<AnnotationsSide>(0);

	public Annotations() {
	}

	public Annotations(long id, Processes processes, Publications publications, Corpus corpus, long annotStart, long annotEnd, String annotType, boolean active) {
		this.id = id;
		this.processes = processes;
		this.publications = publications;
		this.corpus = corpus;
		this.annotStart = annotStart;
		this.annotEnd = annotEnd;
		this.annotType = annotType;
		this.active = active;
	}

	public Annotations(long id, ResourceElements resourceElements, Processes processes, Classes classes, Publications publications, Corpus corpus, long annotStart, long annotEnd, String element, String normalizationForm, String annotType, String clue, String classificationRe,
			boolean active, Long startSentenceOffset, Long endSentenceOffset, String notes, Set<AnnotationsProperties> annotationsPropertieses, Set<AnnotationsSide> annotationsSidesForIdannotationsSubId, Set<AnnotationsLog> annotationsLogs,
			Set<AnnotationsSide> annotationsSidesForAnnotationsId) {
		this.id = id;
		this.resourceElements = resourceElements;
		this.processes = processes;
		this.classes = classes;
		this.publications = publications;
		this.corpus = corpus;
		this.annotStart = annotStart;
		this.annotEnd = annotEnd;
		this.element = element;
		this.normalizationForm = normalizationForm;
		this.annotType = annotType;
		this.clue = clue;
		this.classificationRe = classificationRe;
		this.active = active;
		this.startSentenceOffset = startSentenceOffset;
		this.endSentenceOffset = endSentenceOffset;
		this.notes = notes;
		this.annotationsPropertieses = annotationsPropertieses;
		this.annotationsSidesForIdannotationsSubId = annotationsSidesForIdannotationsSubId;
		this.annotationsLogs = annotationsLogs;
		this.annotationsSidesForAnnotationsId = annotationsSidesForAnnotationsId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_elements_id")
	public ResourceElements getResourceElements() {
		return this.resourceElements;
	}

	public void setResourceElements(ResourceElements resourceElements) {
		this.resourceElements = resourceElements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processes_id", nullable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classes_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publications_id", nullable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corpus_id", nullable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@Column(name = "annot_start", nullable = false)
	public long getAnnotStart() {
		return this.annotStart;
	}

	public void setAnnotStart(long annotStart) {
		this.annotStart = annotStart;
	}

	@Column(name = "annot_end", nullable = false)
	public long getAnnotEnd() {
		return this.annotEnd;
	}

	public void setAnnotEnd(long annotEnd) {
		this.annotEnd = annotEnd;
	}

	@Column(name = "element", length = 500)
	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	@Column(name = "normalization_form", length = 500)
	public String getNormalizationForm() {
		return this.normalizationForm;
	}

	public void setNormalizationForm(String normalizationForm) {
		this.normalizationForm = normalizationForm;
	}

	@Column(name = "annot_type", nullable = false, length = 4)
	public String getAnnotType() {
		return this.annotType;
	}

	public void setAnnotType(String annotType) {
		this.annotType = annotType;
	}

	@Column(name = "clue", length = 250)
	public String getClue() {
		return this.clue;
	}

	public void setClue(String clue) {
		this.clue = clue;
	}

	@Column(name = "classification_re", length = 250)
	public String getClassificationRe() {
		return this.classificationRe;
	}

	public void setClassificationRe(String classificationRe) {
		this.classificationRe = classificationRe;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "start_sentence_offset")
	public Long getStartSentenceOffset() {
		return this.startSentenceOffset;
	}

	public void setStartSentenceOffset(Long startSentenceOffset) {
		this.startSentenceOffset = startSentenceOffset;
	}

	@Column(name = "end_sentence_offset")
	public Long getEndSentenceOffset() {
		return this.endSentenceOffset;
	}

	public void setEndSentenceOffset(Long endSentenceOffset) {
		this.endSentenceOffset = endSentenceOffset;
	}

	@Column(name = "notes", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annotations")
	public Set<AnnotationsProperties> getAnnotationsPropertieses() {
		return this.annotationsPropertieses;
	}

	public void setAnnotationsPropertieses(Set<AnnotationsProperties> annotationsPropertieses) {
		this.annotationsPropertieses = annotationsPropertieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annotationsByIdannotationsSubId")
	public Set<AnnotationsSide> getAnnotationsSidesForIdannotationsSubId() {
		return this.annotationsSidesForIdannotationsSubId;
	}

	public void setAnnotationsSidesForIdannotationsSubId(Set<AnnotationsSide> annotationsSidesForIdannotationsSubId) {
		this.annotationsSidesForIdannotationsSubId = annotationsSidesForIdannotationsSubId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annotations")
	public Set<AnnotationsLog> getAnnotationsLogs() {
		return this.annotationsLogs;
	}

	public void setAnnotationsLogs(Set<AnnotationsLog> annotationsLogs) {
		this.annotationsLogs = annotationsLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annotationsByAnnotationsId")
	public Set<AnnotationsSide> getAnnotationsSidesForAnnotationsId() {
		return this.annotationsSidesForAnnotationsId;
	}

	public void setAnnotationsSidesForAnnotationsId(Set<AnnotationsSide> annotationsSidesForAnnotationsId) {
		this.annotationsSidesForAnnotationsId = annotationsSidesForAnnotationsId;
	}

}
