package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnnotationsSideId generated by hbm2java
 */
@Embeddable
public class AnnotationsSideId implements java.io.Serializable {

	private long annotationsId;
	private long idannotationsSubId;

	public AnnotationsSideId() {
	}

	public AnnotationsSideId(long annotationsId, long idannotationsSubId) {
		this.annotationsId = annotationsId;
		this.idannotationsSubId = idannotationsSubId;
	}

	@Column(name = "annotations_id", nullable = false)
	public long getAnnotationsId() {
		return this.annotationsId;
	}

	public void setAnnotationsId(long annotationsId) {
		this.annotationsId = annotationsId;
	}

	@Column(name = "idannotations_sub_id", nullable = false)
	public long getIdannotationsSubId() {
		return this.idannotationsSubId;
	}

	public void setIdannotationsSubId(long idannotationsSubId) {
		this.idannotationsSubId = idannotationsSubId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnnotationsSideId))
			return false;
		AnnotationsSideId castOther = (AnnotationsSideId) other;

		return (this.getAnnotationsId() == castOther.getAnnotationsId()) && (this.getIdannotationsSubId() == castOther.getIdannotationsSubId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnnotationsId();
		result = 37 * result + (int) this.getIdannotationsSubId();
		return result;
	}

}
