package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnnotationsProperties generated by hbm2java
 */
@Entity
@Table(name = "annotations_properties")
public class AnnotationsProperties implements java.io.Serializable {

	private AnnotationsPropertiesId id;
	private Annotations annotations;
	private String propValue;

	public AnnotationsProperties() {
	}

	public AnnotationsProperties(AnnotationsPropertiesId id, Annotations annotations, String propValue) {
		this.id = id;
		this.annotations = annotations;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false)), @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public AnnotationsPropertiesId getId() {
		return this.id;
	}

	public void setId(AnnotationsPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	public Annotations getAnnotations() {
		return this.annotations;
	}

	public void setAnnotations(Annotations annotations) {
		this.annotations = annotations;
	}

	@Column(name = "prop_value", nullable = false)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
