package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClustersProperties generated by hbm2java
 */
@Entity
@Table(name = "clusters_properties")
public class ClustersProperties implements java.io.Serializable {

	private ClustersPropertiesId id;
	private ClustersProcesses clustersProcesses;
	private String propValue;

	public ClustersProperties() {
	}

	public ClustersProperties(ClustersPropertiesId id, ClustersProcesses clustersProcesses, String propValue) {
		this.id = id;
		this.clustersProcesses = clustersProcesses;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "clustersProcessId", column = @Column(name = "clusters_process_id", nullable = false)), @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false, length = 45)) })
	public ClustersPropertiesId getId() {
		return this.id;
	}

	public void setId(ClustersPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clusters_process_id", nullable = false, insertable = false, updatable = false)
	public ClustersProcesses getClustersProcesses() {
		return this.clustersProcesses;
	}

	public void setClustersProcesses(ClustersProcesses clustersProcesses) {
		this.clustersProcesses = clustersProcesses;
	}

	@Column(name = "prop_value", nullable = false, length = 200)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
