package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusPropertiesId generated by hbm2java
 */
@Embeddable
public class CorpusPropertiesId implements java.io.Serializable {

	private long corpusId;
	private String propKey;

	public CorpusPropertiesId() {
	}

	public CorpusPropertiesId(long corpusId, String propKey) {
		this.corpusId = corpusId;
		this.propKey = propKey;
	}

	@Column(name = "corpus_id", nullable = false)
	public long getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(long corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "prop_key", nullable = false, length = 250)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusPropertiesId))
			return false;
		CorpusPropertiesId castOther = (CorpusPropertiesId) other;

		return (this.getCorpusId() == castOther.getCorpusId()) && ((this.getPropKey() == castOther.getPropKey()) || (this.getPropKey() != null && castOther.getPropKey() != null && this.getPropKey().equals(castOther.getPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCorpusId();
		result = 37 * result + (getPropKey() == null ? 0 : this.getPropKey().hashCode());
		return result;
	}

}
