package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessesProperties generated by hbm2java
 */
@Entity
@Table(name = "processes_properties")
public class ProcessesProperties implements java.io.Serializable {

	private ProcessesPropertiesId id;
	private Processes processes;
	private String propValue;

	public ProcessesProperties() {
	}

	public ProcessesProperties(ProcessesPropertiesId id, Processes processes, String propValue) {
		this.id = id;
		this.processes = processes;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "processesId", column = @Column(name = "processes_id", nullable = false)), @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false, length = 250)) })
	public ProcessesPropertiesId getId() {
		return this.id;
	}

	public void setId(ProcessesPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processes_id", nullable = false, insertable = false, updatable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@Column(name = "prop_value", nullable = false, length = 250)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
