package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcessEntitiesStats generated by hbm2java
 */
@Entity
@Table(name = "process_entities_stats")
public class ProcessEntitiesStats implements java.io.Serializable {

	private ProcessEntitiesStatsId id;

	public ProcessEntitiesStats() {
	}

	public ProcessEntitiesStats(ProcessEntitiesStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "processesId", column = @Column(name = "processes_id", nullable = false)), @AttributeOverride(name = "element", column = @Column(name = "element", length = 500)),
			@AttributeOverride(name = "numberElements", column = @Column(name = "numberElements", nullable = false)), @AttributeOverride(name = "class_", column = @Column(name = "class", nullable = false)) })
	public ProcessEntitiesStatsId getId() {
		return this.id;
	}

	public void setId(ProcessEntitiesStatsId id) {
		this.id = id;
	}

}
