package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QueriesPropertiesId generated by hbm2java
 */
@Embeddable
public class QueriesPropertiesId implements java.io.Serializable {

	private long queriesId;
	private String propKey;

	public QueriesPropertiesId() {
	}

	public QueriesPropertiesId(long queriesId, String propKey) {
		this.queriesId = queriesId;
		this.propKey = propKey;
	}

	@Column(name = "queries_id", nullable = false)
	public long getQueriesId() {
		return this.queriesId;
	}

	public void setQueriesId(long queriesId) {
		this.queriesId = queriesId;
	}

	@Column(name = "prop_key", nullable = false, length = 250)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueriesPropertiesId))
			return false;
		QueriesPropertiesId castOther = (QueriesPropertiesId) other;

		return (this.getQueriesId() == castOther.getQueriesId()) && ((this.getPropKey() == castOther.getPropKey()) || (this.getPropKey() != null && castOther.getPropKey() != null && this.getPropKey().equals(castOther.getPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQueriesId();
		result = 37 * result + (getPropKey() == null ? 0 : this.getPropKey().hashCode());
		return result;
	}

}
