package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResourceElementsRelationType generated by hbm2java
 */
@Entity
@Table(name = "resource_elements_relation_type", uniqueConstraints = @UniqueConstraint(columnNames = "relation_type"))
public class ResourceElementsRelationType implements java.io.Serializable {

	private long id;
	private String relationType;
	private Set<ResourceElementsRelation> resourceElementsRelations = new HashSet<ResourceElementsRelation>(0);

	public ResourceElementsRelationType() {
	}

	public ResourceElementsRelationType(long id, String relationType) {
		this.id = id;
		this.relationType = relationType;
	}

	public ResourceElementsRelationType(long id, String relationType, Set<ResourceElementsRelation> resourceElementsRelations) {
		this.id = id;
		this.relationType = relationType;
		this.resourceElementsRelations = resourceElementsRelations;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "relation_type", unique = true, nullable = false, length = 250)
	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElementsRelationType")
	public Set<ResourceElementsRelation> getResourceElementsRelations() {
		return this.resourceElementsRelations;
	}

	public void setResourceElementsRelations(Set<ResourceElementsRelation> resourceElementsRelations) {
		this.resourceElementsRelations = resourceElementsRelations;
	}

}
