package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesTotalElementsSynonyms generated by hbm2java
 */
@Entity
@Table(name = "resources_total_elements_synonyms")
public class ResourcesTotalElementsSynonyms implements java.io.Serializable {

	private ResourcesTotalElementsSynonymsId id;

	public ResourcesTotalElementsSynonyms() {
	}

	public ResourcesTotalElementsSynonyms(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resourcesId", column = @Column(name = "resources_id", nullable = false)), @AttributeOverride(name = "numberSynonyms", column = @Column(name = "numberSynonyms", nullable = false)) })
	public ResourcesTotalElementsSynonymsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

}
