package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsersLog generated by hbm2java
 */
@Entity
@Table(name = "users_log")
public class UsersLog implements java.io.Serializable {

	private Long id;
	private Users users;
	private Date createDate;
	private String operation;
	private String tableChanged;
	private String sqlCommand;
	private String notes;

	public UsersLog() {
	}

	public UsersLog(Users users, Date createDate, String operation, String tableChanged) {
		this.users = users;
		this.createDate = createDate;
		this.operation = operation;
		this.tableChanged = tableChanged;
	}

	public UsersLog(Users users, Date createDate, String operation, String tableChanged, String sqlCommand, String notes) {
		this.users = users;
		this.createDate = createDate;
		this.operation = operation;
		this.tableChanged = tableChanged;
		this.sqlCommand = sqlCommand;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "create_user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "operation", nullable = false, length = 7)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "table_changed", nullable = false, length = 128)
	public String getTableChanged() {
		return this.tableChanged;
	}

	public void setTableChanged(String tableChanged) {
		this.tableChanged = tableChanged;
	}

	@Column(name = "sql_command", length = 16777215)
	public String getSqlCommand() {
		return this.sqlCommand;
	}

	public void setSqlCommand(String sqlCommand) {
		this.sqlCommand = sqlCommand;
	}

	@Column(name = "notes", length = 16777215)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
