package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGeneralSettings generated by hbm2java
 */
@Entity
@Table(name = "users_general_settings")
public class UsersGeneralSettings implements java.io.Serializable {

	private UsersGeneralSettingsId id;
	private Users users;
	private String propValue;

	public UsersGeneralSettings() {
	}

	public UsersGeneralSettings(UsersGeneralSettingsId id, Users users, String propValue) {
		this.id = id;
		this.users = users;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "usersId", column = @Column(name = "users_id", nullable = false)), @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false)) })
	public UsersGeneralSettingsId getId() {
		return this.id;
	}

	public void setId(UsersGeneralSettingsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "prop_value", nullable = false, length = 65535)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
