package com.silicolife.anote2daemon.model.core.pojo;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersGeneralSettingsId generated by hbm2java
 */
@Embeddable
public class UsersGeneralSettingsId implements java.io.Serializable {

	private long usersId;
	private String propKey;

	public UsersGeneralSettingsId() {
	}

	public UsersGeneralSettingsId(long usersId, String propKey) {
		this.usersId = usersId;
		this.propKey = propKey;
	}

	@Column(name = "users_id", nullable = false)
	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	@Column(name = "prop_key", nullable = false)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersGeneralSettingsId))
			return false;
		UsersGeneralSettingsId castOther = (UsersGeneralSettingsId) other;

		return (this.getUsersId() == castOther.getUsersId()) && ((this.getPropKey() == castOther.getPropKey()) || (this.getPropKey() != null && castOther.getPropKey() != null && this.getPropKey().equals(castOther.getPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsersId();
		result = 37 * result + (getPropKey() == null ? 0 : this.getPropKey().hashCode());
		return result;
	}

}
