package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClustersPropertiesId generated by hbm2java
 */
@Embeddable
public class ClustersPropertiesId implements java.io.Serializable {

	private long clustersProcessId;
	private String propKey;

	public ClustersPropertiesId() {
	}

	public ClustersPropertiesId(long clustersProcessId, String propKey) {
		this.clustersProcessId = clustersProcessId;
		this.propKey = propKey;
	}

	@Column(name = "clusters_process_id", nullable = false)
	public long getClustersProcessId() {
		return this.clustersProcessId;
	}

	public void setClustersProcessId(long clustersProcessId) {
		this.clustersProcessId = clustersProcessId;
	}

	@Column(name = "prop_key", nullable = false, length = 45)
	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClustersPropertiesId))
			return false;
		ClustersPropertiesId castOther = (ClustersPropertiesId) other;

		return (this.getClustersProcessId() == castOther.getClustersProcessId()) && ((this.getPropKey() == castOther.getPropKey()) || (this.getPropKey() != null && castOther.getPropKey() != null && this.getPropKey().equals(castOther.getPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClustersProcessId();
		result = 37 * result + (getPropKey() == null ? 0 : this.getPropKey().hashCode());
		return result;
	}

}
