package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusHasProcessesId generated by hbm2java
 */
@Embeddable
public class CorpusHasProcessesId implements java.io.Serializable {

	private long corpusId;
	private long processesId;

	public CorpusHasProcessesId() {
	}

	public CorpusHasProcessesId(long corpusId, long processesId) {
		this.corpusId = corpusId;
		this.processesId = processesId;
	}

	@Column(name = "corpus_id", nullable = false)
	public long getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(long corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "processes_id", nullable = false)
	public long getProcessesId() {
		return this.processesId;
	}

	public void setProcessesId(long processesId) {
		this.processesId = processesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusHasProcessesId))
			return false;
		CorpusHasProcessesId castOther = (CorpusHasProcessesId) other;

		return (this.getCorpusId() == castOther.getCorpusId()) && (this.getProcessesId() == castOther.getProcessesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCorpusId();
		result = 37 * result + (int) this.getProcessesId();
		return result;
	}

}
