package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessEntitiesClassStatsId generated by hbm2java
 */
@Embeddable
public class ProcessEntitiesClassStatsId implements java.io.Serializable {

	private long processesId;
	private String class_;
	private long numberClasses;

	public ProcessEntitiesClassStatsId() {
	}

	public ProcessEntitiesClassStatsId(long processesId, String class_, long numberClasses) {
		this.processesId = processesId;
		this.class_ = class_;
		this.numberClasses = numberClasses;
	}

	@Column(name = "processes_id", nullable = false)
	public long getProcessesId() {
		return this.processesId;
	}

	public void setProcessesId(long processesId) {
		this.processesId = processesId;
	}

	@Column(name = "class", nullable = false)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "numberClasses", nullable = false)
	public long getNumberClasses() {
		return this.numberClasses;
	}

	public void setNumberClasses(long numberClasses) {
		this.numberClasses = numberClasses;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessEntitiesClassStatsId))
			return false;
		ProcessEntitiesClassStatsId castOther = (ProcessEntitiesClassStatsId) other;

		return (this.getProcessesId() == castOther.getProcessesId()) && ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null && castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())))
				&& (this.getNumberClasses() == castOther.getNumberClasses());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProcessesId();
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (int) this.getNumberClasses();
		return result;
	}

}
