package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "users_access_levels", uniqueConstraints = @UniqueConstraint(columnNames = "codes_access_levels"))
public class UsersAccessLevels implements java.io.Serializable {

	private Long id;
	private String codesAccessLevels;
	private String description;
	private Set<UsersGroupsHasUsersAccessLevels> usersGroupsHasUsersAccessLevelses = new HashSet<UsersGroupsHasUsersAccessLevels>(0);

	public UsersAccessLevels() {
	}

	public UsersAccessLevels(String codesAccessLevels, String description) {
		this.codesAccessLevels = codesAccessLevels;
		this.description = description;
	}

	public UsersAccessLevels(String codesAccessLevels, String description, Set<UsersGroupsHasUsersAccessLevels> usersGroupsHasUsersAccessLevelses) {
		this.codesAccessLevels = codesAccessLevels;
		this.description = description;
		this.usersGroupsHasUsersAccessLevelses = usersGroupsHasUsersAccessLevelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "codes_access_levels", unique = true, nullable = false, length = 128)
	public String getCodesAccessLevels() {
		return this.codesAccessLevels;
	}

	public void setCodesAccessLevels(String codesAccessLevels) {
		this.codesAccessLevels = codesAccessLevels;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usersAccessLevels")
	public Set<UsersGroupsHasUsersAccessLevels> getUsersGroupsHasUsersAccessLevelses() {
		return this.usersGroupsHasUsersAccessLevelses;
	}

	public void setUsersGroupsHasUsersAccessLevelses(Set<UsersGroupsHasUsersAccessLevels> usersGroupsHasUsersAccessLevelses) {
		this.usersGroupsHasUsersAccessLevelses = usersGroupsHasUsersAccessLevelses;
	}

}
