package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasDataObject generated by hbm2java
 */
@Entity
@Table(name = "users_has_data_object")
public class UsersHasDataObject implements java.io.Serializable {

	private UsersHasDataObjectId id;
	private Users users;
	private String accesLevel;

	public UsersHasDataObject() {
	}

	public UsersHasDataObject(UsersHasDataObjectId id, Users users, String accesLevel) {
		this.id = id;
		this.users = users;
		this.accesLevel = accesLevel;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "usersId", column = @Column(name = "users_id", nullable = false)), @AttributeOverride(name = "uidResource", column = @Column(name = "uid_resource", nullable = false)),
			@AttributeOverride(name = "typeResources", column = @Column(name = "type_resources", nullable = false, length = 9)) })
	public UsersHasDataObjectId getId() {
		return this.id;
	}

	public void setId(UsersHasDataObjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "acces_level", nullable = false, length = 10)
	public String getAccesLevel() {
		return this.accesLevel;
	}

	public void setAccesLevel(String accesLevel) {
		this.accesLevel = accesLevel;
	}

}
