package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnnotationsSide generated by hbm2java
 */
@Entity
@Table(name = "annotations_side")
public class AnnotationsSide implements java.io.Serializable {

	private AnnotationsSideId id;
	private Annotations annotationsByIdannotationsSubId;
	private Annotations annotationsByAnnotationsId;
	private String type;

	public AnnotationsSide() {
	}

	public AnnotationsSide(AnnotationsSideId id, Annotations annotationsByIdannotationsSubId, Annotations annotationsByAnnotationsId, String type) {
		this.id = id;
		this.annotationsByIdannotationsSubId = annotationsByIdannotationsSubId;
		this.annotationsByAnnotationsId = annotationsByAnnotationsId;
		this.type = type;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "annotationsId", column = @Column(name = "annotations_id", nullable = false)), @AttributeOverride(name = "idannotationsSubId", column = @Column(name = "idannotations_sub_id", nullable = false)) })
	public AnnotationsSideId getId() {
		return this.id;
	}

	public void setId(AnnotationsSideId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idannotations_sub_id", nullable = false, insertable = false, updatable = false)
	public Annotations getAnnotationsByIdannotationsSubId() {
		return this.annotationsByIdannotationsSubId;
	}

	public void setAnnotationsByIdannotationsSubId(Annotations annotationsByIdannotationsSubId) {
		this.annotationsByIdannotationsSubId = annotationsByIdannotationsSubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annotations_id", nullable = false, insertable = false, updatable = false)
	public Annotations getAnnotationsByAnnotationsId() {
		return this.annotationsByAnnotationsId;
	}

	public void setAnnotationsByAnnotationsId(Annotations annotationsByAnnotationsId) {
		this.annotationsByAnnotationsId = annotationsByAnnotationsId;
	}

	@Column(name = "type", nullable = false, length = 5)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
