package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * AnnotationsSideId generated by hbm2java
 */
public class AnnotationsSideId implements java.io.Serializable {

	private long idannotations;
	private long idannotationsSub;

	public AnnotationsSideId() {
	}

	public AnnotationsSideId(long idannotations, long idannotationsSub) {
		this.idannotations = idannotations;
		this.idannotationsSub = idannotationsSub;
	}

	public long getIdannotations() {
		return this.idannotations;
	}

	public void setIdannotations(long idannotations) {
		this.idannotations = idannotations;
	}

	public long getIdannotationsSub() {
		return this.idannotationsSub;
	}

	public void setIdannotationsSub(long idannotationsSub) {
		this.idannotationsSub = idannotationsSub;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnnotationsSideId))
			return false;
		AnnotationsSideId castOther = (AnnotationsSideId) other;

		return (this.getIdannotations() == castOther.getIdannotations()) && (this.getIdannotationsSub() == castOther.getIdannotationsSub());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdannotations();
		result = 37 * result + (int) this.getIdannotationsSub();
		return result;
	}

}
