package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AnnotationsLog generated by hbm2java
 */
public class AnnotationsLog implements java.io.Serializable {

	private long id;
	private Annotations annotations;
	private Publications publications;
	private Processes processes;
	private Corpus corpus;
	private String type;
	private String old;
	private String new_;
	private String notes;
	private Date date;

	public AnnotationsLog() {
	}

	public AnnotationsLog(long id, Publications publications, Processes processes, Corpus corpus, String type, String old, String new_, Date date) {
		this.id = id;
		this.publications = publications;
		this.processes = processes;
		this.corpus = corpus;
		this.type = type;
		this.old = old;
		this.new_ = new_;
		this.date = date;
	}

	public AnnotationsLog(long id, Annotations annotations, Publications publications, Processes processes, Corpus corpus, String type, String old, String new_, String notes, Date date) {
		this.id = id;
		this.annotations = annotations;
		this.publications = publications;
		this.processes = processes;
		this.corpus = corpus;
		this.type = type;
		this.old = old;
		this.new_ = new_;
		this.notes = notes;
		this.date = date;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Annotations getAnnotations() {
		return this.annotations;
	}

	public void setAnnotations(Annotations annotations) {
		this.annotations = annotations;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOld() {
		return this.old;
	}

	public void setOld(String old) {
		this.old = old;
	}

	public String getNew_() {
		return this.new_;
	}

	public void setNew_(String new_) {
		this.new_ = new_;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
