package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * AnnotationsSide generated by hbm2java
 */
public class AnnotationsSide implements java.io.Serializable {

	private AnnotationsSideId id;
	private Annotations annotationsByIdannotationsSubId;
	private Annotations annotationsByAnnotationsId;
	private String type;

	public AnnotationsSide() {
	}

	public AnnotationsSide(AnnotationsSideId id, Annotations annotationsByIdannotationsSubId, Annotations annotationsByAnnotationsId, String type) {
		this.id = id;
		this.annotationsByIdannotationsSubId = annotationsByIdannotationsSubId;
		this.annotationsByAnnotationsId = annotationsByAnnotationsId;
		this.type = type;
	}

	public AnnotationsSideId getId() {
		return this.id;
	}

	public void setId(AnnotationsSideId id) {
		this.id = id;
	}

	public Annotations getAnnotationsByIdannotationsSubId() {
		return this.annotationsByIdannotationsSubId;
	}

	public void setAnnotationsByIdannotationsSubId(Annotations annotationsByIdannotationsSubId) {
		this.annotationsByIdannotationsSubId = annotationsByIdannotationsSubId;
	}

	public Annotations getAnnotationsByAnnotationsId() {
		return this.annotationsByAnnotationsId;
	}

	public void setAnnotationsByAnnotationsId(Annotations annotationsByAnnotationsId) {
		this.annotationsByAnnotationsId = annotationsByAnnotationsId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
