package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassesHierarchy generated by hbm2java
 */
@Entity
@Table(name = "classes_hierarchy")
public class ClassesHierarchy implements java.io.Serializable {

	private ClassesHierarchyId id;
	private Classes classesByClassesId;
	private Classes classesBySuperClassId;

	public ClassesHierarchy() {
	}

	public ClassesHierarchy(ClassesHierarchyId id, Classes classesByClassesId, Classes classesBySuperClassId) {
		this.id = id;
		this.classesByClassesId = classesByClassesId;
		this.classesBySuperClassId = classesBySuperClassId;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "classesId", column = @Column(name = "classes_id", nullable = false)), @AttributeOverride(name = "superClassId", column = @Column(name = "super_class_id", nullable = false)) })
	public ClassesHierarchyId getId() {
		return this.id;
	}

	public void setId(ClassesHierarchyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classes_id", nullable = false, insertable = false, updatable = false)
	public Classes getClassesByClassesId() {
		return this.classesByClassesId;
	}

	public void setClassesByClassesId(Classes classesByClassesId) {
		this.classesByClassesId = classesByClassesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "super_class_id", nullable = false, insertable = false, updatable = false)
	public Classes getClassesBySuperClassId() {
		return this.classesBySuperClassId;
	}

	public void setClassesBySuperClassId(Classes classesBySuperClassId) {
		this.classesBySuperClassId = classesBySuperClassId;
	}

}
