package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ClassHierarchyId generated by hbm2java
 */
public class ClassHierarchyId implements java.io.Serializable {

	private long classesIdclasses;
	private long superclass;

	public ClassHierarchyId() {
	}

	public ClassHierarchyId(long classesIdclasses, long superclass) {
		this.classesIdclasses = classesIdclasses;
		this.superclass = superclass;
	}

	public long getClassesIdclasses() {
		return this.classesIdclasses;
	}

	public void setClassesIdclasses(long classesIdclasses) {
		this.classesIdclasses = classesIdclasses;
	}

	public long getSuperclass() {
		return this.superclass;
	}

	public void setSuperclass(long superclass) {
		this.superclass = superclass;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassHierarchyId))
			return false;
		ClassHierarchyId castOther = (ClassHierarchyId) other;

		return (this.getClassesIdclasses() == castOther.getClassesIdclasses()) && (this.getSuperclass() == castOther.getSuperclass());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClassesIdclasses();
		result = 37 * result + (int) this.getSuperclass();
		return result;
	}

}
