package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassesHierarchyId generated by hbm2java
 */
@Embeddable
public class ClassesHierarchyId implements java.io.Serializable {

	private long classesId;
	private long superClassId;

	public ClassesHierarchyId() {
	}

	public ClassesHierarchyId(long classesId, long superClassId) {
		this.classesId = classesId;
		this.superClassId = superClassId;
	}

	@Column(name = "classes_id", nullable = false)
	public long getClassesId() {
		return this.classesId;
	}

	public void setClassesId(long classesId) {
		this.classesId = classesId;
	}

	@Column(name = "super_class_id", nullable = false)
	public long getSuperClassId() {
		return this.superClassId;
	}

	public void setSuperClassId(long superClassId) {
		this.superClassId = superClassId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassesHierarchyId))
			return false;
		ClassesHierarchyId castOther = (ClassesHierarchyId) other;

		return (this.getClassesId() == castOther.getClassesId()) && (this.getSuperClassId() == castOther.getSuperClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClassesId();
		result = 37 * result + (int) this.getSuperClassId();
		return result;
	}

}
