package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ClassesColors generated by hbm2java
 */
public class ClassesColors implements java.io.Serializable {

	private long classesId;
	private Classes classes;
	private String color;

	public ClassesColors() {
	}

	public ClassesColors(Classes classes) {
		this.classes = classes;
	}

	public ClassesColors(Classes classes, String color) {
		this.classes = classes;
		this.color = color;
	}

	public long getClassesId() {
		return this.classesId;
	}

	public void setClassesId(long classesId) {
		this.classesId = classesId;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
