package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ClassHierarchy generated by hbm2java
 */
public class ClassHierarchy implements java.io.Serializable {

	private ClassHierarchyId id;
	private Classes classesByClassesId;
	private Classes classesBySuperClassId;

	public ClassHierarchy() {
	}

	public ClassHierarchy(ClassHierarchyId id, Classes classesByClassesId, Classes classesBySuperClassId) {
		this.id = id;
		this.classesByClassesId = classesByClassesId;
		this.classesBySuperClassId = classesBySuperClassId;
	}

	public ClassHierarchyId getId() {
		return this.id;
	}

	public void setId(ClassHierarchyId id) {
		this.id = id;
	}

	public Classes getClassesByClassesId() {
		return this.classesByClassesId;
	}

	public void setClassesByClassesId(Classes classesByClassesId) {
		this.classesByClassesId = classesByClassesId;
	}

	public Classes getClassesBySuperClassId() {
		return this.classesBySuperClassId;
	}

	public void setClassesBySuperClassId(Classes classesBySuperClassId) {
		this.classesBySuperClassId = classesBySuperClassId;
	}

}
