package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Long idclasses;
	private String class_;
	private Set<ResourcesContent> resourcesContents = new HashSet<ResourcesContent>(0);
	private ClassesColors classesColors;
	private Set<Annotations> annotationses = new HashSet<Annotations>(0);
	private Set<ClassHierarchy> classHierarchiesForClassesIdclasses = new HashSet<ClassHierarchy>(0);
	private Set<ClassHierarchy> classHierarchiesForSuperclass = new HashSet<ClassHierarchy>(0);

	public Classes() {
	}

	public Classes(String class_) {
		this.class_ = class_;
	}

	public Classes(String class_, Set<ResourcesContent> resourcesContents, ClassesColors classesColors, Set<Annotations> annotationses, Set<ClassHierarchy> classHierarchiesForClassesIdclasses, Set<ClassHierarchy> classHierarchiesForSuperclass) {
		this.class_ = class_;
		this.resourcesContents = resourcesContents;
		this.classesColors = classesColors;
		this.annotationses = annotationses;
		this.classHierarchiesForClassesIdclasses = classHierarchiesForClassesIdclasses;
		this.classHierarchiesForSuperclass = classHierarchiesForSuperclass;
	}

	public Long getIdclasses() {
		return this.idclasses;
	}

	public void setIdclasses(Long idclasses) {
		this.idclasses = idclasses;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Set<ResourcesContent> getResourcesContents() {
		return this.resourcesContents;
	}

	public void setResourcesContents(Set<ResourcesContent> resourcesContents) {
		this.resourcesContents = resourcesContents;
	}

	public ClassesColors getClassesColors() {
		return this.classesColors;
	}

	public void setClassesColors(ClassesColors classesColors) {
		this.classesColors = classesColors;
	}

	public Set<Annotations> getAnnotationses() {
		return this.annotationses;
	}

	public void setAnnotationses(Set<Annotations> annotationses) {
		this.annotationses = annotationses;
	}

	public Set<ClassHierarchy> getClassHierarchiesForClassesIdclasses() {
		return this.classHierarchiesForClassesIdclasses;
	}

	public void setClassHierarchiesForClassesIdclasses(Set<ClassHierarchy> classHierarchiesForClassesIdclasses) {
		this.classHierarchiesForClassesIdclasses = classHierarchiesForClassesIdclasses;
	}

	public Set<ClassHierarchy> getClassHierarchiesForSuperclass() {
		return this.classHierarchiesForSuperclass;
	}

	public void setClassHierarchiesForSuperclass(Set<ClassHierarchy> classHierarchiesForSuperclass) {
		this.classHierarchiesForSuperclass = classHierarchiesForSuperclass;
	}

}
