package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * ClassHierarchy generated by hbm2java
 */
public class ClassHierarchy implements java.io.Serializable {

	private ClassHierarchyId id;
	private Classes classesBySuperclass;
	private Classes classesByClassesIdclasses;

	public ClassHierarchy() {
	}

	public ClassHierarchy(ClassHierarchyId id, Classes classesBySuperclass, Classes classesByClassesIdclasses) {
		this.id = id;
		this.classesBySuperclass = classesBySuperclass;
		this.classesByClassesIdclasses = classesByClassesIdclasses;
	}

	public ClassHierarchyId getId() {
		return this.id;
	}

	public void setId(ClassHierarchyId id) {
		this.id = id;
	}

	public Classes getClassesBySuperclass() {
		return this.classesBySuperclass;
	}

	public void setClassesBySuperclass(Classes classesBySuperclass) {
		this.classesBySuperclass = classesBySuperclass;
	}

	public Classes getClassesByClassesIdclasses() {
		return this.classesByClassesIdclasses;
	}

	public void setClassesByClassesIdclasses(Classes classesByClassesIdclasses) {
		this.classesByClassesIdclasses = classesByClassesIdclasses;
	}

}
