package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ClustersLabelsDocumentsId generated by hbm2java
 */
public class ClustersLabelsDocumentsId implements java.io.Serializable {

	private long clustersLabelsId;
	private long queriesIdqueries;
	private long publicationsId;

	public ClustersLabelsDocumentsId() {
	}

	public ClustersLabelsDocumentsId(long clustersLabelsId, long queriesIdqueries, long publicationsId) {
		this.clustersLabelsId = clustersLabelsId;
		this.queriesIdqueries = queriesIdqueries;
		this.publicationsId = publicationsId;
	}

	public long getClustersLabelsId() {
		return this.clustersLabelsId;
	}

	public void setClustersLabelsId(long clustersLabelsId) {
		this.clustersLabelsId = clustersLabelsId;
	}

	public long getQueriesIdqueries() {
		return this.queriesIdqueries;
	}

	public void setQueriesIdqueries(long queriesIdqueries) {
		this.queriesIdqueries = queriesIdqueries;
	}

	public long getPublicationsId() {
		return this.publicationsId;
	}

	public void setPublicationsId(long publicationsId) {
		this.publicationsId = publicationsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClustersLabelsDocumentsId))
			return false;
		ClustersLabelsDocumentsId castOther = (ClustersLabelsDocumentsId) other;

		return (this.getClustersLabelsId() == castOther.getClustersLabelsId()) && (this.getQueriesIdqueries() == castOther.getQueriesIdqueries()) && (this.getPublicationsId() == castOther.getPublicationsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClustersLabelsId();
		result = 37 * result + (int) this.getQueriesIdqueries();
		result = 37 * result + (int) this.getPublicationsId();
		return result;
	}

}
