package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClustersProcessHasClustersLabelsId generated by hbm2java
 */
@Embeddable
public class ClustersProcessHasClustersLabelsId implements java.io.Serializable {

	private long clustersProcessId;
	private long clustersLabelsId;

	public ClustersProcessHasClustersLabelsId() {
	}

	public ClustersProcessHasClustersLabelsId(long clustersProcessId, long clustersLabelsId) {
		this.clustersProcessId = clustersProcessId;
		this.clustersLabelsId = clustersLabelsId;
	}

	@Column(name = "clusters_process_id", nullable = false)
	public long getClustersProcessId() {
		return this.clustersProcessId;
	}

	public void setClustersProcessId(long clustersProcessId) {
		this.clustersProcessId = clustersProcessId;
	}

	@Column(name = "clusters_labels_id", nullable = false)
	public long getClustersLabelsId() {
		return this.clustersLabelsId;
	}

	public void setClustersLabelsId(long clustersLabelsId) {
		this.clustersLabelsId = clustersLabelsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClustersProcessHasClustersLabelsId))
			return false;
		ClustersProcessHasClustersLabelsId castOther = (ClustersProcessHasClustersLabelsId) other;

		return (this.getClustersProcessId() == castOther.getClustersProcessId()) && (this.getClustersLabelsId() == castOther.getClustersLabelsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClustersProcessId();
		result = 37 * result + (int) this.getClustersLabelsId();
		return result;
	}

}
