package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClustersLabels generated by hbm2java
 */
@Entity
@Table(name = "clusters_labels")
public class ClustersLabels implements java.io.Serializable {

	private long clustersLabelId;
	private String name;
	private Double score;
	private Set<ClustersLabelsPublications> clustersLabelsPublicationses = new HashSet<ClustersLabelsPublications>(0);
	private Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses = new HashSet<ClustersProcessHasClustersLabels>(0);

	public ClustersLabels() {
	}

	public ClustersLabels(long clustersLabelId, String name) {
		this.clustersLabelId = clustersLabelId;
		this.name = name;
	}

	public ClustersLabels(long clustersLabelId, String name, Double score, Set<ClustersLabelsPublications> clustersLabelsPublicationses, Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses) {
		this.clustersLabelId = clustersLabelId;
		this.name = name;
		this.score = score;
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
		this.clustersProcessHasClustersLabelses = clustersProcessHasClustersLabelses;
	}

	@Id
	@Column(name = "clusters_label_id", unique = true, nullable = false)
	public long getClustersLabelId() {
		return this.clustersLabelId;
	}

	public void setClustersLabelId(long clustersLabelId) {
		this.clustersLabelId = clustersLabelId;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "score", precision = 22, scale = 0)
	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clustersLabels")
	public Set<ClustersLabelsPublications> getClustersLabelsPublicationses() {
		return this.clustersLabelsPublicationses;
	}

	public void setClustersLabelsPublicationses(Set<ClustersLabelsPublications> clustersLabelsPublicationses) {
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clustersLabels")
	public Set<ClustersProcessHasClustersLabels> getClustersProcessHasClustersLabelses() {
		return this.clustersProcessHasClustersLabelses;
	}

	public void setClustersProcessHasClustersLabelses(Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses) {
		this.clustersProcessHasClustersLabelses = clustersProcessHasClustersLabelses;
	}

}
