package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClustersProcessHasClustersLabels generated by hbm2java
 */
@Entity
@Table(name = "clusters_process_has_clusters_labels")
public class ClustersProcessHasClustersLabels implements java.io.Serializable {

	private ClustersProcessHasClustersLabelsId id;
	private ClustersLabels clustersLabels;
	private ClustersProcesses clustersProcesses;

	public ClustersProcessHasClustersLabels() {
	}

	public ClustersProcessHasClustersLabels(ClustersProcessHasClustersLabelsId id, ClustersLabels clustersLabels, ClustersProcesses clustersProcesses) {
		this.id = id;
		this.clustersLabels = clustersLabels;
		this.clustersProcesses = clustersProcesses;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "clustersProcessId", column = @Column(name = "clusters_process_id", nullable = false)), @AttributeOverride(name = "clustersLabelsId", column = @Column(name = "clusters_labels_id", nullable = false)) })
	public ClustersProcessHasClustersLabelsId getId() {
		return this.id;
	}

	public void setId(ClustersProcessHasClustersLabelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clusters_labels_id", nullable = false, insertable = false, updatable = false)
	public ClustersLabels getClustersLabels() {
		return this.clustersLabels;
	}

	public void setClustersLabels(ClustersLabels clustersLabels) {
		this.clustersLabels = clustersLabels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clusters_process_id", nullable = false, insertable = false, updatable = false)
	public ClustersProcesses getClustersProcesses() {
		return this.clustersProcesses;
	}

	public void setClustersProcesses(ClustersProcesses clustersProcesses) {
		this.clustersProcesses = clustersProcesses;
	}

}
