package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClustersProperties generated by hbm2java
 */
@Entity
@Table(name = "clusters_properties")
public class ClustersProperties implements java.io.Serializable {

	private ClustersPropertiesId id;
	private ClustersProcesses clustersProcesses;
	private String value;

	public ClustersProperties() {
	}

	public ClustersProperties(ClustersPropertiesId id, ClustersProcesses clustersProcesses, String value) {
		this.id = id;
		this.clustersProcesses = clustersProcesses;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "clustersProcessId", column = @Column(name = "clusters_process_id", nullable = false)), @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 45)) })
	public ClustersPropertiesId getId() {
		return this.id;
	}

	public void setId(ClustersPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clusters_process_id", nullable = false, insertable = false, updatable = false)
	public ClustersProcesses getClustersProcesses() {
		return this.clustersProcesses;
	}

	public void setClustersProcesses(ClustersProcesses clustersProcesses) {
		this.clustersProcesses = clustersProcesses;
	}

	@Column(name = "value", nullable = false, length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
