package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ClustersProcessHasClustersLabels generated by hbm2java
 */
public class ClustersProcessHasClustersLabels implements java.io.Serializable {

	private ClustersProcessHasClustersLabelsId id;
	private ClustersProcess clustersProcess;
	private ClustersLabels clustersLabels;

	public ClustersProcessHasClustersLabels() {
	}

	public ClustersProcessHasClustersLabels(ClustersProcessHasClustersLabelsId id, ClustersProcess clustersProcess, ClustersLabels clustersLabels) {
		this.id = id;
		this.clustersProcess = clustersProcess;
		this.clustersLabels = clustersLabels;
	}

	public ClustersProcessHasClustersLabelsId getId() {
		return this.id;
	}

	public void setId(ClustersProcessHasClustersLabelsId id) {
		this.id = id;
	}

	public ClustersProcess getClustersProcess() {
		return this.clustersProcess;
	}

	public void setClustersProcess(ClustersProcess clustersProcess) {
		this.clustersProcess = clustersProcess;
	}

	public ClustersLabels getClustersLabels() {
		return this.clustersLabels;
	}

	public void setClustersLabels(ClustersLabels clustersLabels) {
		this.clustersLabels = clustersLabels;
	}

}
