package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ClustersLabels generated by hbm2java
 */
public class ClustersLabels implements java.io.Serializable {

	private long clustersLabelId;
	private String name;
	private Double score;
	private Set<ClustersLabelsPublications> clustersLabelsPublicationses = new HashSet<ClustersLabelsPublications>(0);
	private Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses = new HashSet<ClustersProcessHasClustersLabels>(0);

	public ClustersLabels() {
	}

	public ClustersLabels(long clustersLabelId, String name) {
		this.clustersLabelId = clustersLabelId;
		this.name = name;
	}

	public ClustersLabels(long clustersLabelId, String name, Double score, Set<ClustersLabelsPublications> clustersLabelsPublicationses, Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses) {
		this.clustersLabelId = clustersLabelId;
		this.name = name;
		this.score = score;
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
		this.clustersProcessHasClustersLabelses = clustersProcessHasClustersLabelses;
	}

	public long getClustersLabelId() {
		return this.clustersLabelId;
	}

	public void setClustersLabelId(long clustersLabelId) {
		this.clustersLabelId = clustersLabelId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	public Set<ClustersLabelsPublications> getClustersLabelsPublicationses() {
		return this.clustersLabelsPublicationses;
	}

	public void setClustersLabelsPublicationses(Set<ClustersLabelsPublications> clustersLabelsPublicationses) {
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
	}

	public Set<ClustersProcessHasClustersLabels> getClustersProcessHasClustersLabelses() {
		return this.clustersProcessHasClustersLabelses;
	}

	public void setClustersProcessHasClustersLabelses(Set<ClustersProcessHasClustersLabels> clustersProcessHasClustersLabelses) {
		this.clustersProcessHasClustersLabelses = clustersProcessHasClustersLabelses;
	}

}
