package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CodesAccessLevels generated by hbm2java
 */
public class CodesAccessLevels implements java.io.Serializable {

	private Long id;
	private String code;
	private String description;
	private Set<AccessLevels> accessLevelses = new HashSet<AccessLevels>(0);

	public CodesAccessLevels() {
	}

	public CodesAccessLevels(String code) {
		this.code = code;
	}

	public CodesAccessLevels(String code, String description, Set<AccessLevels> accessLevelses) {
		this.code = code;
		this.description = description;
		this.accessLevelses = accessLevelses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<AccessLevels> getAccessLevelses() {
		return this.accessLevelses;
	}

	public void setAccessLevelses(Set<AccessLevels> accessLevelses) {
		this.accessLevelses = accessLevelses;
	}

}
