package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * CorpusHasPublications generated by hbm2java
 */
public class CorpusHasPublications implements java.io.Serializable {

	private CorpusHasPublicationsId id;
	private Publications publications;
	private Corpus corpus;

	public CorpusHasPublications() {
	}

	public CorpusHasPublications(CorpusHasPublicationsId id, Publications publications, Corpus corpus) {
		this.id = id;
		this.publications = publications;
		this.corpus = corpus;
	}

	public CorpusHasPublicationsId getId() {
		return this.id;
	}

	public void setId(CorpusHasPublicationsId id) {
		this.id = id;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

}
