package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * CorpusHasProcesses generated by hbm2java
 */
public class CorpusHasProcesses implements java.io.Serializable {

	private CorpusHasProcessesId id;
	private Processes processes;
	private Corpus corpus;

	public CorpusHasProcesses() {
	}

	public CorpusHasProcesses(CorpusHasProcessesId id, Processes processes, Corpus corpus) {
		this.id = id;
		this.processes = processes;
		this.corpus = corpus;
	}

	public CorpusHasProcessesId getId() {
		return this.id;
	}

	public void setId(CorpusHasProcessesId id) {
		this.id = id;
	}

	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

}
