package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorpusProperties generated by hbm2java
 */
@Entity
@Table(name = "corpus_properties")
public class CorpusProperties implements java.io.Serializable {

	private CorpusPropertiesId id;
	private Corpus corpus;
	private String value;

	public CorpusProperties() {
	}

	public CorpusProperties(CorpusPropertiesId id, Corpus corpus, String value) {
		this.id = id;
		this.corpus = corpus;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "corpusId", column = @Column(name = "corpus_id", nullable = false)), @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 250)) })
	public CorpusPropertiesId getId() {
		return this.id;
	}

	public void setId(CorpusPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corpus_id", nullable = false, insertable = false, updatable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
