package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusPropertiesId generated by hbm2java
 */
@Embeddable
public class CorpusPropertiesId implements java.io.Serializable {

	private long corpusId;
	private String key;

	public CorpusPropertiesId() {
	}

	public CorpusPropertiesId(long corpusId, String key) {
		this.corpusId = corpusId;
		this.key = key;
	}

	@Column(name = "corpus_id", nullable = false)
	public long getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(long corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "key", nullable = false, length = 250)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusPropertiesId))
			return false;
		CorpusPropertiesId castOther = (CorpusPropertiesId) other;

		return (this.getCorpusId() == castOther.getCorpusId()) && ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCorpusId();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
