package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DaemonGroupsHasAccessLevelsId generated by hbm2java
 */
@Embeddable
public class DaemonGroupsHasAccessLevelsId implements java.io.Serializable {

	private long groupsId;
	private long accessLevelsId;

	public DaemonGroupsHasAccessLevelsId() {
	}

	public DaemonGroupsHasAccessLevelsId(long groupsId, long accessLevelsId) {
		this.groupsId = groupsId;
		this.accessLevelsId = accessLevelsId;
	}

	@Column(name = "groups_id", nullable = false)
	public long getGroupsId() {
		return this.groupsId;
	}

	public void setGroupsId(long groupsId) {
		this.groupsId = groupsId;
	}

	@Column(name = "access_levels_id", nullable = false)
	public long getAccessLevelsId() {
		return this.accessLevelsId;
	}

	public void setAccessLevelsId(long accessLevelsId) {
		this.accessLevelsId = accessLevelsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DaemonGroupsHasAccessLevelsId))
			return false;
		DaemonGroupsHasAccessLevelsId castOther = (DaemonGroupsHasAccessLevelsId) other;

		return (this.getGroupsId() == castOther.getGroupsId()) && (this.getAccessLevelsId() == castOther.getAccessLevelsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGroupsId();
		result = 37 * result + (int) this.getAccessLevelsId();
		return result;
	}

}
