package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DaemonUsersHasDataObjectId generated by hbm2java
 */
@Embeddable
public class DaemonUsersHasDataObjectId implements java.io.Serializable {

	private long usersId;
	private long uidResource;
	private long typeResourcesId;

	public DaemonUsersHasDataObjectId() {
	}

	public DaemonUsersHasDataObjectId(long usersId, long uidResource, long typeResourcesId) {
		this.usersId = usersId;
		this.uidResource = uidResource;
		this.typeResourcesId = typeResourcesId;
	}

	@Column(name = "users_id", nullable = false)
	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	@Column(name = "uid_resource", nullable = false)
	public long getUidResource() {
		return this.uidResource;
	}

	public void setUidResource(long uidResource) {
		this.uidResource = uidResource;
	}

	@Column(name = "type_resources_id", nullable = false)
	public long getTypeResourcesId() {
		return this.typeResourcesId;
	}

	public void setTypeResourcesId(long typeResourcesId) {
		this.typeResourcesId = typeResourcesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DaemonUsersHasDataObjectId))
			return false;
		DaemonUsersHasDataObjectId castOther = (DaemonUsersHasDataObjectId) other;

		return (this.getUsersId() == castOther.getUsersId()) && (this.getUidResource() == castOther.getUidResource()) && (this.getTypeResourcesId() == castOther.getTypeResourcesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsersId();
		result = 37 * result + (int) this.getUidResource();
		result = 37 * result + (int) this.getTypeResourcesId();
		return result;
	}

}
