package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DaemonAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "daemon_access_levels", uniqueConstraints = @UniqueConstraint(columnNames = "codes_access_levels"))
public class DaemonAccessLevels implements java.io.Serializable {

	private Long id;
	private String codesAccessLevels;
	private String description;
	private Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses = new HashSet<DaemonGroupsHasAccessLevels>(0);

	public DaemonAccessLevels() {
	}

	public DaemonAccessLevels(String codesAccessLevels, String description) {
		this.codesAccessLevels = codesAccessLevels;
		this.description = description;
	}

	public DaemonAccessLevels(String codesAccessLevels, String description, Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses) {
		this.codesAccessLevels = codesAccessLevels;
		this.description = description;
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "codes_access_levels", unique = true, nullable = false, length = 128)
	public String getCodesAccessLevels() {
		return this.codesAccessLevels;
	}

	public void setCodesAccessLevels(String codesAccessLevels) {
		this.codesAccessLevels = codesAccessLevels;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daemonAccessLevels")
	public Set<DaemonGroupsHasAccessLevels> getDaemonGroupsHasAccessLevelses() {
		return this.daemonGroupsHasAccessLevelses;
	}

	public void setDaemonGroupsHasAccessLevelses(Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses) {
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
	}

}
