package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DaemonAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "daemon_access_levels")
public class DaemonAccessLevels implements java.io.Serializable {

	private Long id;
	private DaemonCodesAccessLevels daemonCodesAccessLevels;
	private String description;
	private Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses = new HashSet<DaemonGroupsHasAccessLevels>(0);

	public DaemonAccessLevels() {
	}

	public DaemonAccessLevels(DaemonCodesAccessLevels daemonCodesAccessLevels, String description) {
		this.daemonCodesAccessLevels = daemonCodesAccessLevels;
		this.description = description;
	}

	public DaemonAccessLevels(DaemonCodesAccessLevels daemonCodesAccessLevels, String description, Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses) {
		this.daemonCodesAccessLevels = daemonCodesAccessLevels;
		this.description = description;
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codes_access_levels_id", nullable = false)
	public DaemonCodesAccessLevels getDaemonCodesAccessLevels() {
		return this.daemonCodesAccessLevels;
	}

	public void setDaemonCodesAccessLevels(DaemonCodesAccessLevels daemonCodesAccessLevels) {
		this.daemonCodesAccessLevels = daemonCodesAccessLevels;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daemonAccessLevels")
	public Set<DaemonGroupsHasAccessLevels> getDaemonGroupsHasAccessLevelses() {
		return this.daemonGroupsHasAccessLevelses;
	}

	public void setDaemonGroupsHasAccessLevelses(Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses) {
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
	}

}
