package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DaemonGroupsHasAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "daemon_groups_has_access_levels")
public class DaemonGroupsHasAccessLevels implements java.io.Serializable {

	private DaemonGroupsHasAccessLevelsId id;
	private DaemonGroups daemonGroups;
	private DaemonAccessLevels daemonAccessLevels;

	public DaemonGroupsHasAccessLevels() {
	}

	public DaemonGroupsHasAccessLevels(DaemonGroupsHasAccessLevelsId id, DaemonGroups daemonGroups, DaemonAccessLevels daemonAccessLevels) {
		this.id = id;
		this.daemonGroups = daemonGroups;
		this.daemonAccessLevels = daemonAccessLevels;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "groupsId", column = @Column(name = "groups_id", nullable = false)), @AttributeOverride(name = "accessLevelsId", column = @Column(name = "access_levels_id", nullable = false)) })
	public DaemonGroupsHasAccessLevelsId getId() {
		return this.id;
	}

	public void setId(DaemonGroupsHasAccessLevelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groups_id", nullable = false, insertable = false, updatable = false)
	public DaemonGroups getDaemonGroups() {
		return this.daemonGroups;
	}

	public void setDaemonGroups(DaemonGroups daemonGroups) {
		this.daemonGroups = daemonGroups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "access_levels_id", nullable = false, insertable = false, updatable = false)
	public DaemonAccessLevels getDaemonAccessLevels() {
		return this.daemonAccessLevels;
	}

	public void setDaemonAccessLevels(DaemonAccessLevels daemonAccessLevels) {
		this.daemonAccessLevels = daemonAccessLevels;
	}

}
