package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DaemonCodesAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "daemon_codes_access_levels", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class DaemonCodesAccessLevels implements java.io.Serializable {

	private Long id;
	private String code;
	private String description;
	private Set<DaemonAccessLevels> daemonAccessLevelses = new HashSet<DaemonAccessLevels>(0);

	public DaemonCodesAccessLevels() {
	}

	public DaemonCodesAccessLevels(String code) {
		this.code = code;
	}

	public DaemonCodesAccessLevels(String code, String description, Set<DaemonAccessLevels> daemonAccessLevelses) {
		this.code = code;
		this.description = description;
		this.daemonAccessLevelses = daemonAccessLevelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 128)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daemonCodesAccessLevels")
	public Set<DaemonAccessLevels> getDaemonAccessLevelses() {
		return this.daemonAccessLevelses;
	}

	public void setDaemonAccessLevelses(Set<DaemonAccessLevels> daemonAccessLevelses) {
		this.daemonAccessLevelses = daemonAccessLevelses;
	}

}
