package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DaemonGroups generated by hbm2java
 */
@Entity
@Table(name = "daemon_groups", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
public class DaemonGroups implements java.io.Serializable {

	private Long id;
	private String description;
	private Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses = new HashSet<DaemonGroupsHasAccessLevels>(0);
	private Set<DaemonUsers> daemonUserses = new HashSet<DaemonUsers>(0);

	public DaemonGroups() {
	}

	public DaemonGroups(String description) {
		this.description = description;
	}

	public DaemonGroups(String description, Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses, Set<DaemonUsers> daemonUserses) {
		this.description = description;
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
		this.daemonUserses = daemonUserses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "description", unique = true, nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daemonGroups")
	public Set<DaemonGroupsHasAccessLevels> getDaemonGroupsHasAccessLevelses() {
		return this.daemonGroupsHasAccessLevelses;
	}

	public void setDaemonGroupsHasAccessLevelses(Set<DaemonGroupsHasAccessLevels> daemonGroupsHasAccessLevelses) {
		this.daemonGroupsHasAccessLevelses = daemonGroupsHasAccessLevelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daemonGroups")
	public Set<DaemonUsers> getDaemonUserses() {
		return this.daemonUserses;
	}

	public void setDaemonUserses(Set<DaemonUsers> daemonUserses) {
		this.daemonUserses = daemonUserses;
	}

}
