package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DataObject generated by hbm2java
 */
public class DataObject implements java.io.Serializable {

	private DataObjectId id;
	private TypeResources typeResources;
	private Set<UsersHasDataObject> usersHasDataObjects = new HashSet<UsersHasDataObject>(0);

	public DataObject() {
	}

	public DataObject(DataObjectId id, TypeResources typeResources) {
		this.id = id;
		this.typeResources = typeResources;
	}

	public DataObject(DataObjectId id, TypeResources typeResources, Set<UsersHasDataObject> usersHasDataObjects) {
		this.id = id;
		this.typeResources = typeResources;
		this.usersHasDataObjects = usersHasDataObjects;
	}

	public DataObjectId getId() {
		return this.id;
	}

	public void setId(DataObjectId id) {
		this.id = id;
	}

	public TypeResources getTypeResources() {
		return this.typeResources;
	}

	public void setTypeResources(TypeResources typeResources) {
		this.typeResources = typeResources;
	}

	public Set<UsersHasDataObject> getUsersHasDataObjects() {
		return this.usersHasDataObjects;
	}

	public void setUsersHasDataObjects(Set<UsersHasDataObject> usersHasDataObjects) {
		this.usersHasDataObjects = usersHasDataObjects;
	}

}
