package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * GroupsHasAccessLevels generated by hbm2java
 */
public class GroupsHasAccessLevels implements java.io.Serializable {

	private GroupsHasAccessLevelsId id;
	private Groups groups;
	private AccessLevels accessLevels;

	public GroupsHasAccessLevels() {
	}

	public GroupsHasAccessLevels(GroupsHasAccessLevelsId id, Groups groups, AccessLevels accessLevels) {
		this.id = id;
		this.groups = groups;
		this.accessLevels = accessLevels;
	}

	public GroupsHasAccessLevelsId getId() {
		return this.id;
	}

	public void setId(GroupsHasAccessLevelsId id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public AccessLevels getAccessLevels() {
		return this.accessLevels;
	}

	public void setAccessLevels(AccessLevels accessLevels) {
		this.accessLevels = accessLevels;
	}

}
