package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private Long id;
	private String description;
	private Set<GroupsHasAccessLevels> groupsHasAccessLevelses = new HashSet<GroupsHasAccessLevels>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Groups() {
	}

	public Groups(String description) {
		this.description = description;
	}

	public Groups(String description, Set<GroupsHasAccessLevels> groupsHasAccessLevelses, Set<Users> userses) {
		this.description = description;
		this.groupsHasAccessLevelses = groupsHasAccessLevelses;
		this.userses = userses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<GroupsHasAccessLevels> getGroupsHasAccessLevelses() {
		return this.groupsHasAccessLevelses;
	}

	public void setGroupsHasAccessLevelses(Set<GroupsHasAccessLevels> groupsHasAccessLevelses) {
		this.groupsHasAccessLevelses = groupsHasAccessLevelses;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
