package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * GroupsHasAccessLevelsId generated by hbm2java
 */
public class GroupsHasAccessLevelsId implements java.io.Serializable {

	private long groupsId;
	private long accessLevelsId;

	public GroupsHasAccessLevelsId() {
	}

	public GroupsHasAccessLevelsId(long groupsId, long accessLevelsId) {
		this.groupsId = groupsId;
		this.accessLevelsId = accessLevelsId;
	}

	public long getGroupsId() {
		return this.groupsId;
	}

	public void setGroupsId(long groupsId) {
		this.groupsId = groupsId;
	}

	public long getAccessLevelsId() {
		return this.accessLevelsId;
	}

	public void setAccessLevelsId(long accessLevelsId) {
		this.accessLevelsId = accessLevelsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupsHasAccessLevelsId))
			return false;
		GroupsHasAccessLevelsId castOther = (GroupsHasAccessLevelsId) other;

		return (this.getGroupsId() == castOther.getGroupsId()) && (this.getAccessLevelsId() == castOther.getAccessLevelsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGroupsId();
		result = 37 * result + (int) this.getAccessLevelsId();
		return result;
	}

}
