package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * HypherLinkMenuSourceAssociationId generated by hbm2java
 */
public class HypherLinkMenuSourceAssociationId implements java.io.Serializable {

	private long hypherLinksMenuId;
	private long sourcesId;

	public HypherLinkMenuSourceAssociationId() {
	}

	public HypherLinkMenuSourceAssociationId(long hypherLinksMenuId, long sourcesId) {
		this.hypherLinksMenuId = hypherLinksMenuId;
		this.sourcesId = sourcesId;
	}

	public long getHypherLinksMenuId() {
		return this.hypherLinksMenuId;
	}

	public void setHypherLinksMenuId(long hypherLinksMenuId) {
		this.hypherLinksMenuId = hypherLinksMenuId;
	}

	public long getSourcesId() {
		return this.sourcesId;
	}

	public void setSourcesId(long sourcesId) {
		this.sourcesId = sourcesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HypherLinkMenuSourceAssociationId))
			return false;
		HypherLinkMenuSourceAssociationId castOther = (HypherLinkMenuSourceAssociationId) other;

		return (this.getHypherLinksMenuId() == castOther.getHypherLinksMenuId()) && (this.getSourcesId() == castOther.getSourcesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHypherLinksMenuId();
		result = 37 * result + (int) this.getSourcesId();
		return result;
	}

}
