package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * HypherLinkMenuSourceAssociation generated by hbm2java
 */
public class HypherLinkMenuSourceAssociation implements java.io.Serializable {

	private HypherLinkMenuSourceAssociationId id;
	private Sources sources;
	private HypherLinksMenu hypherLinksMenu;

	public HypherLinkMenuSourceAssociation() {
	}

	public HypherLinkMenuSourceAssociation(HypherLinkMenuSourceAssociationId id, Sources sources, HypherLinksMenu hypherLinksMenu) {
		this.id = id;
		this.sources = sources;
		this.hypherLinksMenu = hypherLinksMenu;
	}

	public HypherLinkMenuSourceAssociationId getId() {
		return this.id;
	}

	public void setId(HypherLinkMenuSourceAssociationId id) {
		this.id = id;
	}

	public Sources getSources() {
		return this.sources;
	}

	public void setSources(Sources sources) {
		this.sources = sources;
	}

	public HypherLinksMenu getHypherLinksMenu() {
		return this.hypherLinksMenu;
	}

	public void setHypherLinksMenu(HypherLinksMenu hypherLinksMenu) {
		this.hypherLinksMenu = hypherLinksMenu;
	}

}
