package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * HypherLinkMenuSourceAssociationId generated by hbm2java
 */
public class HypherLinkMenuSourceAssociationId implements java.io.Serializable {

	private long hypherLinksMenuId;
	private long sourcesIdsources;

	public HypherLinkMenuSourceAssociationId() {
	}

	public HypherLinkMenuSourceAssociationId(long hypherLinksMenuId, long sourcesIdsources) {
		this.hypherLinksMenuId = hypherLinksMenuId;
		this.sourcesIdsources = sourcesIdsources;
	}

	public long getHypherLinksMenuId() {
		return this.hypherLinksMenuId;
	}

	public void setHypherLinksMenuId(long hypherLinksMenuId) {
		this.hypherLinksMenuId = hypherLinksMenuId;
	}

	public long getSourcesIdsources() {
		return this.sourcesIdsources;
	}

	public void setSourcesIdsources(long sourcesIdsources) {
		this.sourcesIdsources = sourcesIdsources;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HypherLinkMenuSourceAssociationId))
			return false;
		HypherLinkMenuSourceAssociationId castOther = (HypherLinkMenuSourceAssociationId) other;

		return (this.getHypherLinksMenuId() == castOther.getHypherLinksMenuId()) && (this.getSourcesIdsources() == castOther.getSourcesIdsources());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHypherLinksMenuId();
		result = 37 * result + (int) this.getSourcesIdsources();
		return result;
	}

}
