package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HypherLinksSubmenus generated by hbm2java
 */
@Entity
@Table(name = "hypher_links_submenus")
public class HypherLinksSubmenus implements java.io.Serializable {

	private HypherLinksSubmenusId id;
	private HypherLinksMenu hypherLinksMenuByHypherLinksMenuId;
	private HypherLinksMenu hypherLinksMenuByHypherLinksSubmenuId;

	public HypherLinksSubmenus() {
	}

	public HypherLinksSubmenus(HypherLinksSubmenusId id, HypherLinksMenu hypherLinksMenuByHypherLinksMenuId, HypherLinksMenu hypherLinksMenuByHypherLinksSubmenuId) {
		this.id = id;
		this.hypherLinksMenuByHypherLinksMenuId = hypherLinksMenuByHypherLinksMenuId;
		this.hypherLinksMenuByHypherLinksSubmenuId = hypherLinksMenuByHypherLinksSubmenuId;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "hypherLinksMenuId", column = @Column(name = "hypher_links_menu_id", nullable = false)), @AttributeOverride(name = "hypherLinksSubmenuId", column = @Column(name = "hypher_links_submenu_id", nullable = false)) })
	public HypherLinksSubmenusId getId() {
		return this.id;
	}

	public void setId(HypherLinksSubmenusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hypher_links_menu_id", nullable = false, insertable = false, updatable = false)
	public HypherLinksMenu getHypherLinksMenuByHypherLinksMenuId() {
		return this.hypherLinksMenuByHypherLinksMenuId;
	}

	public void setHypherLinksMenuByHypherLinksMenuId(HypherLinksMenu hypherLinksMenuByHypherLinksMenuId) {
		this.hypherLinksMenuByHypherLinksMenuId = hypherLinksMenuByHypherLinksMenuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hypher_links_submenu_id", nullable = false, insertable = false, updatable = false)
	public HypherLinksMenu getHypherLinksMenuByHypherLinksSubmenuId() {
		return this.hypherLinksMenuByHypherLinksSubmenuId;
	}

	public void setHypherLinksMenuByHypherLinksSubmenuId(HypherLinksMenu hypherLinksMenuByHypherLinksSubmenuId) {
		this.hypherLinksMenuByHypherLinksSubmenuId = hypherLinksMenuByHypherLinksSubmenuId;
	}

}
