package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ProcessEntitiesStats generated by hbm2java
 */
public class ProcessEntitiesStats implements java.io.Serializable {

	private ProcessEntitiesStatsId id;

	public ProcessEntitiesStats() {
	}

	public ProcessEntitiesStats(ProcessEntitiesStatsId id) {
		this.id = id;
	}

	public ProcessEntitiesStatsId getId() {
		return this.id;
	}

	public void setId(ProcessEntitiesStatsId id) {
		this.id = id;
	}

}
