package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ProcessesProperties generated by hbm2java
 */
public class ProcessesProperties implements java.io.Serializable {

	private ProcessesPropertiesId id;
	private Processes processes;
	private String value;

	public ProcessesProperties() {
	}

	public ProcessesProperties(ProcessesPropertiesId id, Processes processes, String value) {
		this.id = id;
		this.processes = processes;
		this.value = value;
	}

	public ProcessesPropertiesId getId() {
		return this.id;
	}

	public void setId(ProcessesPropertiesId id) {
		this.id = id;
	}

	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
