package com.silicolife.anote2daemon.model.pojo;
// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0



/**
 * ProcessGeneralResumeStatsId generated by hbm2java
 */
public class ProcessGeneralResumeStatsId  implements java.io.Serializable {


     private long processesIdprocesses;
     private String type;
     private long count(type);

    public ProcessGeneralResumeStatsId() {
    }

    public ProcessGeneralResumeStatsId(long processesIdprocesses, String type, long count(type)) {
       this.processesIdprocesses = processesIdprocesses;
       this.type = type;
       this.count(type) = count(type);
    }
   
    public long getProcessesIdprocesses() {
        return this.processesIdprocesses;
    }
    
    public void setProcessesIdprocesses(long processesIdprocesses) {
        this.processesIdprocesses = processesIdprocesses;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public long getCount(type)() {
        return this.count(type);
    }
    
    public void setCount(type)(long count(type)) {
        this.count(type) = count(type);
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessGeneralResumeStatsId) ) return false;
		 ProcessGeneralResumeStatsId castOther = ( ProcessGeneralResumeStatsId ) other; 
         
		 return (this.getProcessesIdprocesses()==castOther.getProcessesIdprocesses())
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && (this.getCount(type)()==castOther.getCount(type)());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProcessesIdprocesses();
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + (int) this.getCount(type)();
         return result;
   }   


}


