package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ProcessGeneralResumeStats generated by hbm2java
 */
public class ProcessGeneralResumeStats implements java.io.Serializable {

	private ProcessGeneralResumeStatsId id;

	public ProcessGeneralResumeStats() {
	}

	public ProcessGeneralResumeStats(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

	public ProcessGeneralResumeStatsId getId() {
		return this.id;
	}

	public void setId(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

}
