package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ProcessEntitiesStatsId generated by hbm2java
 */
public class ProcessEntitiesStatsId implements java.io.Serializable {

	private long processesIdprocesses;
	private String element;
	private long numberElements;
	private String class_;

	public ProcessEntitiesStatsId() {
	}

	public ProcessEntitiesStatsId(long processesIdprocesses, long numberElements, String class_) {
		this.processesIdprocesses = processesIdprocesses;
		this.numberElements = numberElements;
		this.class_ = class_;
	}

	public ProcessEntitiesStatsId(long processesIdprocesses, String element, long numberElements, String class_) {
		this.processesIdprocesses = processesIdprocesses;
		this.element = element;
		this.numberElements = numberElements;
		this.class_ = class_;
	}

	public long getProcessesIdprocesses() {
		return this.processesIdprocesses;
	}

	public void setProcessesIdprocesses(long processesIdprocesses) {
		this.processesIdprocesses = processesIdprocesses;
	}

	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	public long getNumberElements() {
		return this.numberElements;
	}

	public void setNumberElements(long numberElements) {
		this.numberElements = numberElements;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessEntitiesStatsId))
			return false;
		ProcessEntitiesStatsId castOther = (ProcessEntitiesStatsId) other;

		return (this.getProcessesIdprocesses() == castOther.getProcessesIdprocesses()) && ((this.getElement() == castOther.getElement()) || (this.getElement() != null && castOther.getElement() != null && this.getElement().equals(castOther.getElement())))
				&& (this.getNumberElements() == castOther.getNumberElements()) && ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null && castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProcessesIdprocesses();
		result = 37 * result + (getElement() == null ? 0 : this.getElement().hashCode());
		result = 37 * result + (int) this.getNumberElements();
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		return result;
	}

}
