package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * ProcessEntitiesClassStats generated by hbm2java
 */
public class ProcessEntitiesClassStats implements java.io.Serializable {

	private ProcessEntitiesClassStatsId id;

	public ProcessEntitiesClassStats() {
	}

	public ProcessEntitiesClassStats(ProcessEntitiesClassStatsId id) {
		this.id = id;
	}

	public ProcessEntitiesClassStatsId getId() {
		return this.id;
	}

	public void setId(ProcessEntitiesClassStatsId id) {
		this.id = id;
	}

}
