package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcessGeneralResumeStats generated by hbm2java
 */
@Entity
@Table(name = "process_general_resume_stats")
public class ProcessGeneralResumeStats implements java.io.Serializable {

	private ProcessGeneralResumeStatsId id;

	public ProcessGeneralResumeStats() {
	}

	public ProcessGeneralResumeStats(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "processesId", column = @Column(name = "processes_id", nullable = false)), @AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 4)),
			@AttributeOverride(name = "numberType", column = @Column(name = "numberType", nullable = false)) })
	public ProcessGeneralResumeStatsId getId() {
		return this.id;
	}

	public void setId(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

}
