package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ProcessOrigin generated by hbm2java
 */
public class ProcessOrigin implements java.io.Serializable {

	private long id;
	private String description;
	private Set<Processes> processeses = new HashSet<Processes>(0);

	public ProcessOrigin() {
	}

	public ProcessOrigin(long id, String description) {
		this.id = id;
		this.description = description;
	}

	public ProcessOrigin(long id, String description, Set<Processes> processeses) {
		this.id = id;
		this.description = description;
		this.processeses = processeses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Processes> getProcesseses() {
		return this.processeses;
	}

	public void setProcesseses(Set<Processes> processeses) {
		this.processeses = processeses;
	}

}
