package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ProcessesPropertiesId generated by hbm2java
 */
public class ProcessesPropertiesId implements java.io.Serializable {

	private long processesId;
	private String key;

	public ProcessesPropertiesId() {
	}

	public ProcessesPropertiesId(long processesId, String key) {
		this.processesId = processesId;
		this.key = key;
	}

	public long getProcessesId() {
		return this.processesId;
	}

	public void setProcessesId(long processesId) {
		this.processesId = processesId;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessesPropertiesId))
			return false;
		ProcessesPropertiesId castOther = (ProcessesPropertiesId) other;

		return (this.getProcessesId() == castOther.getProcessesId()) && ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProcessesId();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
