package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessEntitiesStatsId generated by hbm2java
 */
@Embeddable
public class ProcessEntitiesStatsId implements java.io.Serializable {

	private long processesId;
	private String element;
	private long numberElements;
	private String class_;

	public ProcessEntitiesStatsId() {
	}

	public ProcessEntitiesStatsId(long processesId, long numberElements, String class_) {
		this.processesId = processesId;
		this.numberElements = numberElements;
		this.class_ = class_;
	}

	public ProcessEntitiesStatsId(long processesId, String element, long numberElements, String class_) {
		this.processesId = processesId;
		this.element = element;
		this.numberElements = numberElements;
		this.class_ = class_;
	}

	@Column(name = "processes_id", nullable = false)
	public long getProcessesId() {
		return this.processesId;
	}

	public void setProcessesId(long processesId) {
		this.processesId = processesId;
	}

	@Column(name = "element", length = 500)
	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	@Column(name = "numberElements", nullable = false)
	public long getNumberElements() {
		return this.numberElements;
	}

	public void setNumberElements(long numberElements) {
		this.numberElements = numberElements;
	}

	@Column(name = "class", nullable = false)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessEntitiesStatsId))
			return false;
		ProcessEntitiesStatsId castOther = (ProcessEntitiesStatsId) other;

		return (this.getProcessesId() == castOther.getProcessesId()) && ((this.getElement() == castOther.getElement()) || (this.getElement() != null && castOther.getElement() != null && this.getElement().equals(castOther.getElement())))
				&& (this.getNumberElements() == castOther.getNumberElements()) && ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null && castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProcessesId();
		result = 37 * result + (getElement() == null ? 0 : this.getElement().hashCode());
		result = 37 * result + (int) this.getNumberElements();
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		return result;
	}

}
