package com.silicolife.anote2daemon.model.pojo;
// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0



/**
 * ProcessCluesStatsId generated by hbm2java
 */
public class ProcessCluesStatsId  implements java.io.Serializable {


     private long processesIdprocesses;
     private String clue;
     private long count(clue);
     private String classificationRe;

    public ProcessCluesStatsId() {
    }

	
    public ProcessCluesStatsId(long processesIdprocesses, long count(clue)) {
        this.processesIdprocesses = processesIdprocesses;
        this.count(clue) = count(clue);
    }
    public ProcessCluesStatsId(long processesIdprocesses, String clue, long count(clue), String classificationRe) {
       this.processesIdprocesses = processesIdprocesses;
       this.clue = clue;
       this.count(clue) = count(clue);
       this.classificationRe = classificationRe;
    }
   
    public long getProcessesIdprocesses() {
        return this.processesIdprocesses;
    }
    
    public void setProcessesIdprocesses(long processesIdprocesses) {
        this.processesIdprocesses = processesIdprocesses;
    }
    public String getClue() {
        return this.clue;
    }
    
    public void setClue(String clue) {
        this.clue = clue;
    }
    public long getCount(clue)() {
        return this.count(clue);
    }
    
    public void setCount(clue)(long count(clue)) {
        this.count(clue) = count(clue);
    }
    public String getClassificationRe() {
        return this.classificationRe;
    }
    
    public void setClassificationRe(String classificationRe) {
        this.classificationRe = classificationRe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessCluesStatsId) ) return false;
		 ProcessCluesStatsId castOther = ( ProcessCluesStatsId ) other; 
         
		 return (this.getProcessesIdprocesses()==castOther.getProcessesIdprocesses())
 && ( (this.getClue()==castOther.getClue()) || ( this.getClue()!=null && castOther.getClue()!=null && this.getClue().equals(castOther.getClue()) ) )
 && (this.getCount(clue)()==castOther.getCount(clue)())
 && ( (this.getClassificationRe()==castOther.getClassificationRe()) || ( this.getClassificationRe()!=null && castOther.getClassificationRe()!=null && this.getClassificationRe().equals(castOther.getClassificationRe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProcessesIdprocesses();
         result = 37 * result + ( getClue() == null ? 0 : this.getClue().hashCode() );
         result = 37 * result + (int) this.getCount(clue)();
         result = 37 * result + ( getClassificationRe() == null ? 0 : this.getClassificationRe().hashCode() );
         return result;
   }   


}


