package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProcessesType generated by hbm2java
 */
@Entity
@Table(name = "processes_type", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class ProcessesType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<Processes> processeses = new HashSet<Processes>(0);

	public ProcessesType() {
	}

	public ProcessesType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public ProcessesType(long id, String type, Set<Processes> processeses) {
		this.id = id;
		this.type = type;
		this.processeses = processeses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processesType")
	public Set<Processes> getProcesseses() {
		return this.processeses;
	}

	public void setProcesseses(Set<Processes> processeses) {
		this.processeses = processeses;
	}

}
