package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ProcessCluesStats generated by hbm2java
 */
public class ProcessCluesStats implements java.io.Serializable {

	private ProcessCluesStatsId id;

	public ProcessCluesStats() {
	}

	public ProcessCluesStats(ProcessCluesStatsId id) {
		this.id = id;
	}

	public ProcessCluesStatsId getId() {
		return this.id;
	}

	public void setId(ProcessCluesStatsId id) {
		this.id = id;
	}

}
