package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessesProperties generated by hbm2java
 */
@Entity
@Table(name = "processes_properties")
public class ProcessesProperties implements java.io.Serializable {

	private ProcessesPropertiesId id;
	private Processes processes;
	private String value;

	public ProcessesProperties() {
	}

	public ProcessesProperties(ProcessesPropertiesId id, Processes processes, String value) {
		this.id = id;
		this.processes = processes;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "processesId", column = @Column(name = "processes_id", nullable = false)), @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 250)) })
	public ProcessesPropertiesId getId() {
		return this.id;
	}

	public void setId(ProcessesPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processes_id", nullable = false, insertable = false, updatable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@Column(name = "value", nullable = false, length = 250)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
