package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * PublicationsIdType generated by hbm2java
 */
public class PublicationsIdType implements java.io.Serializable {

	private Long idType;
	private String name;

	public PublicationsIdType() {
	}

	public PublicationsIdType(String name) {
		this.name = name;
	}

	public Long getIdType() {
		return this.idType;
	}

	public void setIdType(Long idType) {
		this.idType = idType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
