package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * PublictaionQueryRelevance generated by hbm2java
 */
public class PublictaionQueryRelevance implements java.io.Serializable {

	private PublictaionQueryRelevanceId id;
	private Queries queries;
	private Publications publications;
	private String relevanceEnum;

	public PublictaionQueryRelevance() {
	}

	public PublictaionQueryRelevance(PublictaionQueryRelevanceId id, Queries queries, Publications publications) {
		this.id = id;
		this.queries = queries;
		this.publications = publications;
	}

	public PublictaionQueryRelevance(PublictaionQueryRelevanceId id, Queries queries, Publications publications, String relevanceEnum) {
		this.id = id;
		this.queries = queries;
		this.publications = publications;
		this.relevanceEnum = relevanceEnum;
	}

	public PublictaionQueryRelevanceId getId() {
		return this.id;
	}

	public void setId(PublictaionQueryRelevanceId id) {
		this.id = id;
	}

	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	public String getRelevanceEnum() {
		return this.relevanceEnum;
	}

	public void setRelevanceEnum(String relevanceEnum) {
		this.relevanceEnum = relevanceEnum;
	}

}
