package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * PublicationsHasPublicationLabels generated by hbm2java
 */
public class PublicationsHasPublicationLabels implements java.io.Serializable {

	private PublicationsHasPublicationLabelsId id;
	private PublicationsLabels publicationsLabels;
	private Publications publications;

	public PublicationsHasPublicationLabels() {
	}

	public PublicationsHasPublicationLabels(PublicationsHasPublicationLabelsId id, PublicationsLabels publicationsLabels, Publications publications) {
		this.id = id;
		this.publicationsLabels = publicationsLabels;
		this.publications = publications;
	}

	public PublicationsHasPublicationLabelsId getId() {
		return this.id;
	}

	public void setId(PublicationsHasPublicationLabelsId id) {
		this.id = id;
	}

	public PublicationsLabels getPublicationsLabels() {
		return this.publicationsLabels;
	}

	public void setPublicationsLabels(PublicationsLabels publicationsLabels) {
		this.publicationsLabels = publicationsLabels;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

}
