package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PublicationsLabels generated by hbm2java
 */
public class PublicationsLabels implements java.io.Serializable {

	private long id;
	private String description;
	private Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses = new HashSet<PublicationsHasPublicationLabels>(0);

	public PublicationsLabels() {
	}

	public PublicationsLabels(long id, String description) {
		this.id = id;
		this.description = description;
	}

	public PublicationsLabels(long id, String description, Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses) {
		this.id = id;
		this.description = description;
		this.publicationsHasPublicationLabelses = publicationsHasPublicationLabelses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<PublicationsHasPublicationLabels> getPublicationsHasPublicationLabelses() {
		return this.publicationsHasPublicationLabelses;
	}

	public void setPublicationsHasPublicationLabelses(Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses) {
		this.publicationsHasPublicationLabelses = publicationsHasPublicationLabelses;
	}

}
