package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PublicationsFields generated by hbm2java
 */
@Entity
@Table(name = "publications_fields")
public class PublicationsFields implements java.io.Serializable {

	private PublicationsFieldsId id;
	private Publications publications;
	private int start;
	private int end;

	public PublicationsFields() {
	}

	public PublicationsFields(PublicationsFieldsId id, Publications publications, int start, int end) {
		this.id = id;
		this.publications = publications;
		this.start = start;
		this.end = end;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "field", column = @Column(name = "field", nullable = false, length = 200)), @AttributeOverride(name = "publicationsId", column = @Column(name = "publications_id", nullable = false)) })
	public PublicationsFieldsId getId() {
		return this.id;
	}

	public void setId(PublicationsFieldsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publications_id", nullable = false, insertable = false, updatable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@Column(name = "start", nullable = false)
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false)
	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

}
