package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * PublicationsFields generated by hbm2java
 */
public class PublicationsFields implements java.io.Serializable {

	private PublicationsFieldsId id;
	private Publications publications;
	private int start;
	private int end;

	public PublicationsFields() {
	}

	public PublicationsFields(PublicationsFieldsId id, Publications publications, int start, int end) {
		this.id = id;
		this.publications = publications;
		this.start = start;
		this.end = end;
	}

	public PublicationsFieldsId getId() {
		return this.id;
	}

	public void setId(PublicationsFieldsId id) {
		this.id = id;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

}
