package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicationsHasPublicationsSourceId generated by hbm2java
 */
@Embeddable
public class PublicationsHasPublicationsSourceId implements java.io.Serializable {

	private long publicationsId;
	private long publicationsSourceId;
	private String publicationsSourceInternalId;

	public PublicationsHasPublicationsSourceId() {
	}

	public PublicationsHasPublicationsSourceId(long publicationsId, long publicationsSourceId, String publicationsSourceInternalId) {
		this.publicationsId = publicationsId;
		this.publicationsSourceId = publicationsSourceId;
		this.publicationsSourceInternalId = publicationsSourceInternalId;
	}

	@Column(name = "publications_id", nullable = false)
	public long getPublicationsId() {
		return this.publicationsId;
	}

	public void setPublicationsId(long publicationsId) {
		this.publicationsId = publicationsId;
	}

	@Column(name = "publications_source_id", nullable = false)
	public long getPublicationsSourceId() {
		return this.publicationsSourceId;
	}

	public void setPublicationsSourceId(long publicationsSourceId) {
		this.publicationsSourceId = publicationsSourceId;
	}

	@Column(name = "publications_source_internal_id", nullable = false, length = 250)
	public String getPublicationsSourceInternalId() {
		return this.publicationsSourceInternalId;
	}

	public void setPublicationsSourceInternalId(String publicationsSourceInternalId) {
		this.publicationsSourceInternalId = publicationsSourceInternalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicationsHasPublicationsSourceId))
			return false;
		PublicationsHasPublicationsSourceId castOther = (PublicationsHasPublicationsSourceId) other;

		return (this.getPublicationsId() == castOther.getPublicationsId())
				&& (this.getPublicationsSourceId() == castOther.getPublicationsSourceId())
				&& ((this.getPublicationsSourceInternalId() == castOther.getPublicationsSourceInternalId()) || (this.getPublicationsSourceInternalId() != null && castOther.getPublicationsSourceInternalId() != null && this.getPublicationsSourceInternalId().equals(
						castOther.getPublicationsSourceInternalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPublicationsId();
		result = 37 * result + (int) this.getPublicationsSourceId();
		result = 37 * result + (getPublicationsSourceInternalId() == null ? 0 : this.getPublicationsSourceInternalId().hashCode());
		return result;
	}

}
