package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * PublicationsHasPublicationsSource generated by hbm2java
 */
public class PublicationsHasPublicationsSource implements java.io.Serializable {

	private PublicationsHasPublicationsSourceId id;
	private PublicationsSource publicationsSource;
	private Publications publications;

	public PublicationsHasPublicationsSource() {
	}

	public PublicationsHasPublicationsSource(PublicationsHasPublicationsSourceId id, PublicationsSource publicationsSource, Publications publications) {
		this.id = id;
		this.publicationsSource = publicationsSource;
		this.publications = publications;
	}

	public PublicationsHasPublicationsSourceId getId() {
		return this.id;
	}

	public void setId(PublicationsHasPublicationsSourceId id) {
		this.id = id;
	}

	public PublicationsSource getPublicationsSource() {
		return this.publicationsSource;
	}

	public void setPublicationsSource(PublicationsSource publicationsSource) {
		this.publicationsSource = publicationsSource;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

}
