package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * QueriesPropertiesId generated by hbm2java
 */
public class QueriesPropertiesId implements java.io.Serializable {

	private long queriesId;
	private String key;

	public QueriesPropertiesId() {
	}

	public QueriesPropertiesId(long queriesId, String key) {
		this.queriesId = queriesId;
		this.key = key;
	}

	public long getQueriesId() {
		return this.queriesId;
	}

	public void setQueriesId(long queriesId) {
		this.queriesId = queriesId;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueriesPropertiesId))
			return false;
		QueriesPropertiesId castOther = (QueriesPropertiesId) other;

		return (this.getQueriesId() == castOther.getQueriesId()) && ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQueriesId();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
