package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * QueriesPropertiesId generated by hbm2java
 */
public class QueriesPropertiesId implements java.io.Serializable {

	private long queriesIdqueries;
	private String propertyName;

	public QueriesPropertiesId() {
	}

	public QueriesPropertiesId(long queriesIdqueries, String propertyName) {
		this.queriesIdqueries = queriesIdqueries;
		this.propertyName = propertyName;
	}

	public long getQueriesIdqueries() {
		return this.queriesIdqueries;
	}

	public void setQueriesIdqueries(long queriesIdqueries) {
		this.queriesIdqueries = queriesIdqueries;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueriesPropertiesId))
			return false;
		QueriesPropertiesId castOther = (QueriesPropertiesId) other;

		return (this.getQueriesIdqueries() == castOther.getQueriesIdqueries()) && ((this.getPropertyName() == castOther.getPropertyName()) || (this.getPropertyName() != null && castOther.getPropertyName() != null && this.getPropertyName().equals(castOther.getPropertyName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQueriesIdqueries();
		result = 37 * result + (getPropertyName() == null ? 0 : this.getPropertyName().hashCode());
		return result;
	}

}
