package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * QueriesHasPublicationsId generated by hbm2java
 */
public class QueriesHasPublicationsId implements java.io.Serializable {

	private long queriesIdqueries;
	private long publicationsId;

	public QueriesHasPublicationsId() {
	}

	public QueriesHasPublicationsId(long queriesIdqueries, long publicationsId) {
		this.queriesIdqueries = queriesIdqueries;
		this.publicationsId = publicationsId;
	}

	public long getQueriesIdqueries() {
		return this.queriesIdqueries;
	}

	public void setQueriesIdqueries(long queriesIdqueries) {
		this.queriesIdqueries = queriesIdqueries;
	}

	public long getPublicationsId() {
		return this.publicationsId;
	}

	public void setPublicationsId(long publicationsId) {
		this.publicationsId = publicationsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueriesHasPublicationsId))
			return false;
		QueriesHasPublicationsId castOther = (QueriesHasPublicationsId) other;

		return (this.getQueriesIdqueries() == castOther.getQueriesIdqueries()) && (this.getPublicationsId() == castOther.getPublicationsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQueriesIdqueries();
		result = 37 * result + (int) this.getPublicationsId();
		return result;
	}

}
