package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QueriesProperties generated by hbm2java
 */
@Entity
@Table(name = "queries_properties")
public class QueriesProperties implements java.io.Serializable {

	private QueriesPropertiesId id;
	private Queries queries;
	private String value;

	public QueriesProperties() {
	}

	public QueriesProperties(QueriesPropertiesId id, Queries queries, String value) {
		this.id = id;
		this.queries = queries;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "queriesId", column = @Column(name = "queries_id", nullable = false)), @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false, length = 250)) })
	public QueriesPropertiesId getId() {
		return this.id;
	}

	public void setId(QueriesPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "queries_id", nullable = false, insertable = false, updatable = false)
	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	@Column(name = "value", nullable = false, length = 250)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
