package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Queries generated by hbm2java
 */
public class Queries implements java.io.Serializable {

	private long id;
	private QueriesType queriesType;
	private Date date;
	private String keywords;
	private String organism;
	private String completeQuery;
	private Integer matchingPublications;
	private Integer availableAbstracts;
	private Integer downloadedPublications;
	private String name;
	private boolean active;
	private Set<QueriesHasPublications> queriesHasPublicationses = new HashSet<QueriesHasPublications>(0);
	private Set<QueriesProperties> queriesPropertieses = new HashSet<QueriesProperties>(0);
	private Set<QueriesHasClustersProcess> queriesHasClustersProcesses = new HashSet<QueriesHasClustersProcess>(0);
	private Set<PublictaionQueryRelevance> publictaionQueryRelevances = new HashSet<PublictaionQueryRelevance>(0);

	public Queries() {
	}

	public Queries(long id, QueriesType queriesType, Date date, String keywords, boolean active) {
		this.id = id;
		this.queriesType = queriesType;
		this.date = date;
		this.keywords = keywords;
		this.active = active;
	}

	public Queries(long id, QueriesType queriesType, Date date, String keywords, String organism, String completeQuery, Integer matchingPublications, Integer availableAbstracts, Integer downloadedPublications, String name, boolean active,
			Set<QueriesHasPublications> queriesHasPublicationses, Set<QueriesProperties> queriesPropertieses, Set<QueriesHasClustersProcess> queriesHasClustersProcesses, Set<PublictaionQueryRelevance> publictaionQueryRelevances) {
		this.id = id;
		this.queriesType = queriesType;
		this.date = date;
		this.keywords = keywords;
		this.organism = organism;
		this.completeQuery = completeQuery;
		this.matchingPublications = matchingPublications;
		this.availableAbstracts = availableAbstracts;
		this.downloadedPublications = downloadedPublications;
		this.name = name;
		this.active = active;
		this.queriesHasPublicationses = queriesHasPublicationses;
		this.queriesPropertieses = queriesPropertieses;
		this.queriesHasClustersProcesses = queriesHasClustersProcesses;
		this.publictaionQueryRelevances = publictaionQueryRelevances;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QueriesType getQueriesType() {
		return this.queriesType;
	}

	public void setQueriesType(QueriesType queriesType) {
		this.queriesType = queriesType;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	public String getCompleteQuery() {
		return this.completeQuery;
	}

	public void setCompleteQuery(String completeQuery) {
		this.completeQuery = completeQuery;
	}

	public Integer getMatchingPublications() {
		return this.matchingPublications;
	}

	public void setMatchingPublications(Integer matchingPublications) {
		this.matchingPublications = matchingPublications;
	}

	public Integer getAvailableAbstracts() {
		return this.availableAbstracts;
	}

	public void setAvailableAbstracts(Integer availableAbstracts) {
		this.availableAbstracts = availableAbstracts;
	}

	public Integer getDownloadedPublications() {
		return this.downloadedPublications;
	}

	public void setDownloadedPublications(Integer downloadedPublications) {
		this.downloadedPublications = downloadedPublications;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Set<QueriesHasPublications> getQueriesHasPublicationses() {
		return this.queriesHasPublicationses;
	}

	public void setQueriesHasPublicationses(Set<QueriesHasPublications> queriesHasPublicationses) {
		this.queriesHasPublicationses = queriesHasPublicationses;
	}

	public Set<QueriesProperties> getQueriesPropertieses() {
		return this.queriesPropertieses;
	}

	public void setQueriesPropertieses(Set<QueriesProperties> queriesPropertieses) {
		this.queriesPropertieses = queriesPropertieses;
	}

	public Set<QueriesHasClustersProcess> getQueriesHasClustersProcesses() {
		return this.queriesHasClustersProcesses;
	}

	public void setQueriesHasClustersProcesses(Set<QueriesHasClustersProcess> queriesHasClustersProcesses) {
		this.queriesHasClustersProcesses = queriesHasClustersProcesses;
	}

	public Set<PublictaionQueryRelevance> getPublictaionQueryRelevances() {
		return this.publictaionQueryRelevances;
	}

	public void setPublictaionQueryRelevances(Set<PublictaionQueryRelevance> publictaionQueryRelevances) {
		this.publictaionQueryRelevances = publictaionQueryRelevances;
	}

}
