package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * QueriesHasClustersProcessId generated by hbm2java
 */
public class QueriesHasClustersProcessId implements java.io.Serializable {

	private long queriesId;
	private long clustersProcessId;

	public QueriesHasClustersProcessId() {
	}

	public QueriesHasClustersProcessId(long queriesId, long clustersProcessId) {
		this.queriesId = queriesId;
		this.clustersProcessId = clustersProcessId;
	}

	public long getQueriesId() {
		return this.queriesId;
	}

	public void setQueriesId(long queriesId) {
		this.queriesId = queriesId;
	}

	public long getClustersProcessId() {
		return this.clustersProcessId;
	}

	public void setClustersProcessId(long clustersProcessId) {
		this.clustersProcessId = clustersProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueriesHasClustersProcessId))
			return false;
		QueriesHasClustersProcessId castOther = (QueriesHasClustersProcessId) other;

		return (this.getQueriesId() == castOther.getQueriesId()) && (this.getClustersProcessId() == castOther.getClustersProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQueriesId();
		result = 37 * result + (int) this.getClustersProcessId();
		return result;
	}

}
