package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * QueriesHasPublications generated by hbm2java
 */
public class QueriesHasPublications implements java.io.Serializable {

	private QueriesHasPublicationsId id;
	private Queries queries;
	private Publications publications;
	private Set<ClustersLabelsPublications> clustersLabelsPublicationses = new HashSet<ClustersLabelsPublications>(0);

	public QueriesHasPublications() {
	}

	public QueriesHasPublications(QueriesHasPublicationsId id, Queries queries, Publications publications) {
		this.id = id;
		this.queries = queries;
		this.publications = publications;
	}

	public QueriesHasPublications(QueriesHasPublicationsId id, Queries queries, Publications publications, Set<ClustersLabelsPublications> clustersLabelsPublicationses) {
		this.id = id;
		this.queries = queries;
		this.publications = publications;
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
	}

	public QueriesHasPublicationsId getId() {
		return this.id;
	}

	public void setId(QueriesHasPublicationsId id) {
		this.id = id;
	}

	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	public Set<ClustersLabelsPublications> getClustersLabelsPublicationses() {
		return this.clustersLabelsPublicationses;
	}

	public void setClustersLabelsPublicationses(Set<ClustersLabelsPublications> clustersLabelsPublicationses) {
		this.clustersLabelsPublicationses = clustersLabelsPublicationses;
	}

}
