package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * RelationType generated by hbm2java
 */
public class RelationType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<ResourceElementsRelation> resourceElementsRelations = new HashSet<ResourceElementsRelation>(0);

	public RelationType() {
	}

	public RelationType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public RelationType(long id, String type, Set<ResourceElementsRelation> resourceElementsRelations) {
		this.id = id;
		this.type = type;
		this.resourceElementsRelations = resourceElementsRelations;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<ResourceElementsRelation> getResourceElementsRelations() {
		return this.resourceElementsRelations;
	}

	public void setResourceElementsRelations(Set<ResourceElementsRelation> resourceElementsRelations) {
		this.resourceElementsRelations = resourceElementsRelations;
	}

}
