package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ResourcesClassStats generated by hbm2java
 */
public class ResourcesClassStats implements java.io.Serializable {

	private ResourcesClassStatsId id;

	public ResourcesClassStats() {
	}

	public ResourcesClassStats(ResourcesClassStatsId id) {
		this.id = id;
	}

	public ResourcesClassStatsId getId() {
		return this.id;
	}

	public void setId(ResourcesClassStatsId id) {
		this.id = id;
	}

}
