package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourcesTotalElementsId generated by hbm2java
 */
public class ResourcesTotalElementsId implements java.io.Serializable {

	private long resourcesIdresources;
	private long numberElements;

	public ResourcesTotalElementsId() {
	}

	public ResourcesTotalElementsId(long resourcesIdresources, long numberElements) {
		this.resourcesIdresources = resourcesIdresources;
		this.numberElements = numberElements;
	}

	public long getResourcesIdresources() {
		return this.resourcesIdresources;
	}

	public void setResourcesIdresources(long resourcesIdresources) {
		this.resourcesIdresources = resourcesIdresources;
	}

	public long getNumberElements() {
		return this.numberElements;
	}

	public void setNumberElements(long numberElements) {
		this.numberElements = numberElements;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesTotalElementsId))
			return false;
		ResourcesTotalElementsId castOther = (ResourcesTotalElementsId) other;

		return (this.getResourcesIdresources() == castOther.getResourcesIdresources()) && (this.getNumberElements() == castOther.getNumberElements());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesIdresources();
		result = 37 * result + (int) this.getNumberElements();
		return result;
	}

}
