package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourcesClassSynonymsCountId generated by hbm2java
 */
public class ResourcesClassSynonymsCountId implements java.io.Serializable {

	private long resourcesIdresources;
	private Long classesIdclasses;
	private long numberSynonyms;

	public ResourcesClassSynonymsCountId() {
	}

	public ResourcesClassSynonymsCountId(long resourcesIdresources, long numberSynonyms) {
		this.resourcesIdresources = resourcesIdresources;
		this.numberSynonyms = numberSynonyms;
	}

	public ResourcesClassSynonymsCountId(long resourcesIdresources, Long classesIdclasses, long numberSynonyms) {
		this.resourcesIdresources = resourcesIdresources;
		this.classesIdclasses = classesIdclasses;
		this.numberSynonyms = numberSynonyms;
	}

	public long getResourcesIdresources() {
		return this.resourcesIdresources;
	}

	public void setResourcesIdresources(long resourcesIdresources) {
		this.resourcesIdresources = resourcesIdresources;
	}

	public Long getClassesIdclasses() {
		return this.classesIdclasses;
	}

	public void setClassesIdclasses(Long classesIdclasses) {
		this.classesIdclasses = classesIdclasses;
	}

	public long getNumberSynonyms() {
		return this.numberSynonyms;
	}

	public void setNumberSynonyms(long numberSynonyms) {
		this.numberSynonyms = numberSynonyms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesClassSynonymsCountId))
			return false;
		ResourcesClassSynonymsCountId castOther = (ResourcesClassSynonymsCountId) other;

		return (this.getResourcesIdresources() == castOther.getResourcesIdresources())
				&& ((this.getClassesIdclasses() == castOther.getClassesIdclasses()) || (this.getClassesIdclasses() != null && castOther.getClassesIdclasses() != null && this.getClassesIdclasses().equals(castOther.getClassesIdclasses())))
				&& (this.getNumberSynonyms() == castOther.getNumberSynonyms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesIdresources();
		result = 37 * result + (getClassesIdclasses() == null ? 0 : this.getClassesIdclasses().hashCode());
		result = 37 * result + (int) this.getNumberSynonyms();
		return result;
	}

}
