package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResourceElementsRelationType generated by hbm2java
 */
@Entity
@Table(name = "resource_elements_relation_type", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class ResourceElementsRelationType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<ResourceElementsRelation> resourceElementsRelations = new HashSet<ResourceElementsRelation>(0);

	public ResourceElementsRelationType() {
	}

	public ResourceElementsRelationType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public ResourceElementsRelationType(long id, String type, Set<ResourceElementsRelation> resourceElementsRelations) {
		this.id = id;
		this.type = type;
		this.resourceElementsRelations = resourceElementsRelations;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElementsRelationType")
	public Set<ResourceElementsRelation> getResourceElementsRelations() {
		return this.resourceElementsRelations;
	}

	public void setResourceElementsRelations(Set<ResourceElementsRelation> resourceElementsRelations) {
		this.resourceElementsRelations = resourceElementsRelations;
	}

}
