package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ResourcesType generated by hbm2java
 */
public class ResourcesType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public ResourcesType() {
	}

	public ResourcesType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public ResourcesType(long id, String type, Set<Resources> resourceses) {
		this.id = id;
		this.type = type;
		this.resourceses = resourceses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
