package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ResourcesClassSynonymsCount generated by hbm2java
 */
public class ResourcesClassSynonymsCount implements java.io.Serializable {

	private ResourcesClassSynonymsCountId id;

	public ResourcesClassSynonymsCount() {
	}

	public ResourcesClassSynonymsCount(ResourcesClassSynonymsCountId id) {
		this.id = id;
	}

	public ResourcesClassSynonymsCountId getId() {
		return this.id;
	}

	public void setId(ResourcesClassSynonymsCountId id) {
		this.id = id;
	}

}
