package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourceElementsExtenalId generated by hbm2java
 */
public class ResourceElementsExtenalId implements java.io.Serializable {

	private ResourceElementsExtenalIdId id;
	private ResourceElements resourceElements;
	private Sources sources;
	private boolean active;

	public ResourceElementsExtenalId() {
	}

	public ResourceElementsExtenalId(ResourceElementsExtenalIdId id, ResourceElements resourceElements, Sources sources, boolean active) {
		this.id = id;
		this.resourceElements = resourceElements;
		this.sources = sources;
		this.active = active;
	}

	public ResourceElementsExtenalIdId getId() {
		return this.id;
	}

	public void setId(ResourceElementsExtenalIdId id) {
		this.id = id;
	}

	public ResourceElements getResourceElements() {
		return this.resourceElements;
	}

	public void setResourceElements(ResourceElements resourceElements) {
		this.resourceElements = resourceElements;
	}

	public Sources getSources() {
		return this.sources;
	}

	public void setSources(Sources sources) {
		this.sources = sources;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
