package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

/**
 * ResourcesTotalElementsSynonyms generated by hbm2java
 */
public class ResourcesTotalElementsSynonyms implements java.io.Serializable {

	private ResourcesTotalElementsSynonymsId id;

	public ResourcesTotalElementsSynonyms() {
	}

	public ResourcesTotalElementsSynonyms(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

	public ResourcesTotalElementsSynonymsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

}
