package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourcesTotalElementsSynonymsId generated by hbm2java
 */
public class ResourcesTotalElementsSynonymsId implements java.io.Serializable {

	private long resourcesIdresources;
	private long numberSynonyms;

	public ResourcesTotalElementsSynonymsId() {
	}

	public ResourcesTotalElementsSynonymsId(long resourcesIdresources, long numberSynonyms) {
		this.resourcesIdresources = resourcesIdresources;
		this.numberSynonyms = numberSynonyms;
	}

	public long getResourcesIdresources() {
		return this.resourcesIdresources;
	}

	public void setResourcesIdresources(long resourcesIdresources) {
		this.resourcesIdresources = resourcesIdresources;
	}

	public long getNumberSynonyms() {
		return this.numberSynonyms;
	}

	public void setNumberSynonyms(long numberSynonyms) {
		this.numberSynonyms = numberSynonyms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesTotalElementsSynonymsId))
			return false;
		ResourcesTotalElementsSynonymsId castOther = (ResourcesTotalElementsSynonymsId) other;

		return (this.getResourcesIdresources() == castOther.getResourcesIdresources()) && (this.getNumberSynonyms() == castOther.getNumberSynonyms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesIdresources();
		result = 37 * result + (int) this.getNumberSynonyms();
		return result;
	}

}
