package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 13:51:08 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesClassStats generated by hbm2java
 */
@Entity
@Table(name = "resources_class_stats")
public class ResourcesClassStats implements java.io.Serializable {

	private ResourcesClassStatsId id;

	public ResourcesClassStats() {
	}

	public ResourcesClassStats(ResourcesClassStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resourcesId", column = @Column(name = "resources_id", nullable = false)), @AttributeOverride(name = "classesId", column = @Column(name = "classes_id")),
			@AttributeOverride(name = "numberClasses", column = @Column(name = "numberClasses", nullable = false)) })
	public ResourcesClassStatsId getId() {
		return this.id;
	}

	public void setId(ResourcesClassStatsId id) {
		this.id = id;
	}

}
