package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcesContentId generated by hbm2java
 */
@Embeddable
public class ResourcesContentId implements java.io.Serializable {

	private long resourcesId;
	private long classesId;

	public ResourcesContentId() {
	}

	public ResourcesContentId(long resourcesId, long classesId) {
		this.resourcesId = resourcesId;
		this.classesId = classesId;
	}

	@Column(name = "resources_id", nullable = false)
	public long getResourcesId() {
		return this.resourcesId;
	}

	public void setResourcesId(long resourcesId) {
		this.resourcesId = resourcesId;
	}

	@Column(name = "classes_id", nullable = false)
	public long getClassesId() {
		return this.classesId;
	}

	public void setClassesId(long classesId) {
		this.classesId = classesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesContentId))
			return false;
		ResourcesContentId castOther = (ResourcesContentId) other;

		return (this.getResourcesId() == castOther.getResourcesId()) && (this.getClassesId() == castOther.getClassesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesId();
		result = 37 * result + (int) this.getClassesId();
		return result;
	}

}
