package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * ResourceElementsRelationId generated by hbm2java
 */
public class ResourceElementsRelationId implements java.io.Serializable {

	private long idresourceElementsB;
	private long idresourceElementsA;

	public ResourceElementsRelationId() {
	}

	public ResourceElementsRelationId(long idresourceElementsB, long idresourceElementsA) {
		this.idresourceElementsB = idresourceElementsB;
		this.idresourceElementsA = idresourceElementsA;
	}

	public long getIdresourceElementsB() {
		return this.idresourceElementsB;
	}

	public void setIdresourceElementsB(long idresourceElementsB) {
		this.idresourceElementsB = idresourceElementsB;
	}

	public long getIdresourceElementsA() {
		return this.idresourceElementsA;
	}

	public void setIdresourceElementsA(long idresourceElementsA) {
		this.idresourceElementsA = idresourceElementsA;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceElementsRelationId))
			return false;
		ResourceElementsRelationId castOther = (ResourceElementsRelationId) other;

		return (this.getIdresourceElementsB() == castOther.getIdresourceElementsB()) && (this.getIdresourceElementsA() == castOther.getIdresourceElementsA());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdresourceElementsB();
		result = 37 * result + (int) this.getIdresourceElementsA();
		return result;
	}

}
