package com.silicolife.anote2daemon.model.pojo;
// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0



/**
 * ResourcesTotalElementsSynonymsId generated by hbm2java
 */
public class ResourcesTotalElementsSynonymsId  implements java.io.Serializable {


     private long resourcesIdresources;
     private long count(s.resourceElementsIdresourceElements);

    public ResourcesTotalElementsSynonymsId() {
    }

    public ResourcesTotalElementsSynonymsId(long resourcesIdresources, long count(s.resourceElementsIdresourceElements)) {
       this.resourcesIdresources = resourcesIdresources;
       this.count(s.resourceElementsIdresourceElements) = count(s.resourceElementsIdresourceElements);
    }
   
    public long getResourcesIdresources() {
        return this.resourcesIdresources;
    }
    
    public void setResourcesIdresources(long resourcesIdresources) {
        this.resourcesIdresources = resourcesIdresources;
    }
    public long getCount(s.resourceElementsIdresourceElements)() {
        return this.count(s.resourceElementsIdresourceElements);
    }
    
    public void setCount(s.resourceElementsIdresourceElements)(long count(s.resourceElementsIdresourceElements)) {
        this.count(s.resourceElementsIdresourceElements) = count(s.resourceElementsIdresourceElements);
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResourcesTotalElementsSynonymsId) ) return false;
		 ResourcesTotalElementsSynonymsId castOther = ( ResourcesTotalElementsSynonymsId ) other; 
         
		 return (this.getResourcesIdresources()==castOther.getResourcesIdresources())
 && (this.getCount(s.resourceElementsIdresourceElements)()==castOther.getCount(s.resourceElementsIdresourceElements)());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getResourcesIdresources();
         result = 37 * result + (int) this.getCount(s.resourceElementsIdresourceElements)();
         return result;
   }   


}


