package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourceElementsExtenalIdId generated by hbm2java
 */
@Embeddable
public class ResourceElementsExtenalIdId implements java.io.Serializable {

	private long resourceElementsId;
	private long sourcesId;
	private String externalId;

	public ResourceElementsExtenalIdId() {
	}

	public ResourceElementsExtenalIdId(long resourceElementsId, long sourcesId, String externalId) {
		this.resourceElementsId = resourceElementsId;
		this.sourcesId = sourcesId;
		this.externalId = externalId;
	}

	@Column(name = "resource_elements_id", nullable = false)
	public long getResourceElementsId() {
		return this.resourceElementsId;
	}

	public void setResourceElementsId(long resourceElementsId) {
		this.resourceElementsId = resourceElementsId;
	}

	@Column(name = "sources_id", nullable = false)
	public long getSourcesId() {
		return this.sourcesId;
	}

	public void setSourcesId(long sourcesId) {
		this.sourcesId = sourcesId;
	}

	@Column(name = "external_id", nullable = false, length = 200)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceElementsExtenalIdId))
			return false;
		ResourceElementsExtenalIdId castOther = (ResourceElementsExtenalIdId) other;

		return (this.getResourceElementsId() == castOther.getResourceElementsId()) && (this.getSourcesId() == castOther.getSourcesId())
				&& ((this.getExternalId() == castOther.getExternalId()) || (this.getExternalId() != null && castOther.getExternalId() != null && this.getExternalId().equals(castOther.getExternalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourceElementsId();
		result = 37 * result + (int) this.getSourcesId();
		result = 37 * result + (getExternalId() == null ? 0 : this.getExternalId().hashCode());
		return result;
	}

}
