package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourcesElementsPrioreties generated by hbm2java
 */
public class ResourcesElementsPrioreties implements java.io.Serializable {

	private long resourceElementsIdresourceElements;
	private ResourceElements resourceElements;
	private long priorety;

	public ResourcesElementsPrioreties() {
	}

	public ResourcesElementsPrioreties(ResourceElements resourceElements, long priorety) {
		this.resourceElements = resourceElements;
		this.priorety = priorety;
	}

	public long getResourceElementsIdresourceElements() {
		return this.resourceElementsIdresourceElements;
	}

	public void setResourceElementsIdresourceElements(long resourceElementsIdresourceElements) {
		this.resourceElementsIdresourceElements = resourceElementsIdresourceElements;
	}

	public ResourceElements getResourceElements() {
		return this.resourceElements;
	}

	public void setResourceElements(ResourceElements resourceElements) {
		this.resourceElements = resourceElements;
	}

	public long getPriorety() {
		return this.priorety;
	}

	public void setPriorety(long priorety) {
		this.priorety = priorety;
	}

}
