package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * ResourceElementsRelation generated by hbm2java
 */
public class ResourceElementsRelation implements java.io.Serializable {

	private ResourceElementsRelationId id;
	private RelationType relationType;
	private ResourceElements resourceElementsByIdresourceElementsA;
	private ResourceElements resourceElementsByIdresourceElementsB;

	public ResourceElementsRelation() {
	}

	public ResourceElementsRelation(ResourceElementsRelationId id, RelationType relationType, ResourceElements resourceElementsByIdresourceElementsA, ResourceElements resourceElementsByIdresourceElementsB) {
		this.id = id;
		this.relationType = relationType;
		this.resourceElementsByIdresourceElementsA = resourceElementsByIdresourceElementsA;
		this.resourceElementsByIdresourceElementsB = resourceElementsByIdresourceElementsB;
	}

	public ResourceElementsRelationId getId() {
		return this.id;
	}

	public void setId(ResourceElementsRelationId id) {
		this.id = id;
	}

	public RelationType getRelationType() {
		return this.relationType;
	}

	public void setRelationType(RelationType relationType) {
		this.relationType = relationType;
	}

	public ResourceElements getResourceElementsByIdresourceElementsA() {
		return this.resourceElementsByIdresourceElementsA;
	}

	public void setResourceElementsByIdresourceElementsA(ResourceElements resourceElementsByIdresourceElementsA) {
		this.resourceElementsByIdresourceElementsA = resourceElementsByIdresourceElementsA;
	}

	public ResourceElements getResourceElementsByIdresourceElementsB() {
		return this.resourceElementsByIdresourceElementsB;
	}

	public void setResourceElementsByIdresourceElementsB(ResourceElements resourceElementsByIdresourceElementsB) {
		this.resourceElementsByIdresourceElementsB = resourceElementsByIdresourceElementsB;
	}

}
