package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ResourceElements generated by hbm2java
 */
public class ResourceElements implements java.io.Serializable {

	private long id;
	private Resources resources;
	private Long classesId;
	private String element;
	private Integer priorety;
	private boolean active;
	private ResourcesElementsPrioreties resourcesElementsPrioreties;
	private Set<Annotations> annotationses = new HashSet<Annotations>(0);
	private Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdA = new HashSet<ResourceElementsRelation>(0);
	private Set<ResourceElementsExtenalId> resourceElementsExtenalIds = new HashSet<ResourceElementsExtenalId>(0);
	private Set<Synonyms> synonymses = new HashSet<Synonyms>(0);
	private Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdB = new HashSet<ResourceElementsRelation>(0);

	public ResourceElements() {
	}

	public ResourceElements(long id, Resources resources, String element, boolean active) {
		this.id = id;
		this.resources = resources;
		this.element = element;
		this.active = active;
	}

	public ResourceElements(long id, Resources resources, Long classesId, String element, Integer priorety, boolean active, ResourcesElementsPrioreties resourcesElementsPrioreties, Set<Annotations> annotationses,
			Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdA, Set<ResourceElementsExtenalId> resourceElementsExtenalIds, Set<Synonyms> synonymses, Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdB) {
		this.id = id;
		this.resources = resources;
		this.classesId = classesId;
		this.element = element;
		this.priorety = priorety;
		this.active = active;
		this.resourcesElementsPrioreties = resourcesElementsPrioreties;
		this.annotationses = annotationses;
		this.resourceElementsRelationsForResourceElementsIdA = resourceElementsRelationsForResourceElementsIdA;
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
		this.synonymses = synonymses;
		this.resourceElementsRelationsForResourceElementsIdB = resourceElementsRelationsForResourceElementsIdB;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	public Long getClassesId() {
		return this.classesId;
	}

	public void setClassesId(Long classesId) {
		this.classesId = classesId;
	}

	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	public Integer getPriorety() {
		return this.priorety;
	}

	public void setPriorety(Integer priorety) {
		this.priorety = priorety;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public ResourcesElementsPrioreties getResourcesElementsPrioreties() {
		return this.resourcesElementsPrioreties;
	}

	public void setResourcesElementsPrioreties(ResourcesElementsPrioreties resourcesElementsPrioreties) {
		this.resourcesElementsPrioreties = resourcesElementsPrioreties;
	}

	public Set<Annotations> getAnnotationses() {
		return this.annotationses;
	}

	public void setAnnotationses(Set<Annotations> annotationses) {
		this.annotationses = annotationses;
	}

	public Set<ResourceElementsRelation> getResourceElementsRelationsForResourceElementsIdA() {
		return this.resourceElementsRelationsForResourceElementsIdA;
	}

	public void setResourceElementsRelationsForResourceElementsIdA(Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdA) {
		this.resourceElementsRelationsForResourceElementsIdA = resourceElementsRelationsForResourceElementsIdA;
	}

	public Set<ResourceElementsExtenalId> getResourceElementsExtenalIds() {
		return this.resourceElementsExtenalIds;
	}

	public void setResourceElementsExtenalIds(Set<ResourceElementsExtenalId> resourceElementsExtenalIds) {
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
	}

	public Set<Synonyms> getSynonymses() {
		return this.synonymses;
	}

	public void setSynonymses(Set<Synonyms> synonymses) {
		this.synonymses = synonymses;
	}

	public Set<ResourceElementsRelation> getResourceElementsRelationsForResourceElementsIdB() {
		return this.resourceElementsRelationsForResourceElementsIdB;
	}

	public void setResourceElementsRelationsForResourceElementsIdB(Set<ResourceElementsRelation> resourceElementsRelationsForResourceElementsIdB) {
		this.resourceElementsRelationsForResourceElementsIdB = resourceElementsRelationsForResourceElementsIdB;
	}

}
