package com.silicolife.anote2daemon.model.pojo;

// Generated 19/Jan/2015 15:19:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ResourcesType generated by hbm2java
 */
public class ResourcesType implements java.io.Serializable {

	private Long idresourcesType;
	private String type;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public ResourcesType() {
	}

	public ResourcesType(String type) {
		this.type = type;
	}

	public ResourcesType(String type, Set<Resources> resourceses) {
		this.type = type;
		this.resourceses = resourceses;
	}

	public Long getIdresourcesType() {
		return this.idresourcesType;
	}

	public void setIdresourcesType(Long idresourcesType) {
		this.idresourcesType = idresourcesType;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
