package com.silicolife.anote2daemon.model.pojo;

// Generated 27/Jan/2015 18:22:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcesTotalElementsSynonymsId generated by hbm2java
 */
@Embeddable
public class ResourcesTotalElementsSynonymsId implements java.io.Serializable {

	private long resourcesId;
	private long numberSynonyms;

	public ResourcesTotalElementsSynonymsId() {
	}

	public ResourcesTotalElementsSynonymsId(long resourcesId, long numberSynonyms) {
		this.resourcesId = resourcesId;
		this.numberSynonyms = numberSynonyms;
	}

	@Column(name = "resources_id", nullable = false)
	public long getResourcesId() {
		return this.resourcesId;
	}

	public void setResourcesId(long resourcesId) {
		this.resourcesId = resourcesId;
	}

	@Column(name = "numberSynonyms", nullable = false)
	public long getNumberSynonyms() {
		return this.numberSynonyms;
	}

	public void setNumberSynonyms(long numberSynonyms) {
		this.numberSynonyms = numberSynonyms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesTotalElementsSynonymsId))
			return false;
		ResourcesTotalElementsSynonymsId castOther = (ResourcesTotalElementsSynonymsId) other;

		return (this.getResourcesId() == castOther.getResourcesId()) && (this.getNumberSynonyms() == castOther.getNumberSynonyms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesId();
		result = 37 * result + (int) this.getNumberSynonyms();
		return result;
	}

}
