package com.silicolife.anote2daemon.model.pojo;
// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0



/**
 * ResourcesClassStatsId generated by hbm2java
 */
public class ResourcesClassStatsId  implements java.io.Serializable {


     private long resourcesIdresources;
     private Long classesIdclasses;
     private long count(classesIdclasses);

    public ResourcesClassStatsId() {
    }

	
    public ResourcesClassStatsId(long resourcesIdresources, long count(classesIdclasses)) {
        this.resourcesIdresources = resourcesIdresources;
        this.count(classesIdclasses) = count(classesIdclasses);
    }
    public ResourcesClassStatsId(long resourcesIdresources, Long classesIdclasses, long count(classesIdclasses)) {
       this.resourcesIdresources = resourcesIdresources;
       this.classesIdclasses = classesIdclasses;
       this.count(classesIdclasses) = count(classesIdclasses);
    }
   
    public long getResourcesIdresources() {
        return this.resourcesIdresources;
    }
    
    public void setResourcesIdresources(long resourcesIdresources) {
        this.resourcesIdresources = resourcesIdresources;
    }
    public Long getClassesIdclasses() {
        return this.classesIdclasses;
    }
    
    public void setClassesIdclasses(Long classesIdclasses) {
        this.classesIdclasses = classesIdclasses;
    }
    public long getCount(classesIdclasses)() {
        return this.count(classesIdclasses);
    }
    
    public void setCount(classesIdclasses)(long count(classesIdclasses)) {
        this.count(classesIdclasses) = count(classesIdclasses);
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResourcesClassStatsId) ) return false;
		 ResourcesClassStatsId castOther = ( ResourcesClassStatsId ) other; 
         
		 return (this.getResourcesIdresources()==castOther.getResourcesIdresources())
 && ( (this.getClassesIdclasses()==castOther.getClassesIdclasses()) || ( this.getClassesIdclasses()!=null && castOther.getClassesIdclasses()!=null && this.getClassesIdclasses().equals(castOther.getClassesIdclasses()) ) )
 && (this.getCount(classesIdclasses)()==castOther.getCount(classesIdclasses)());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getResourcesIdresources();
         result = 37 * result + ( getClassesIdclasses() == null ? 0 : this.getClassesIdclasses().hashCode() );
         result = 37 * result + (int) this.getCount(classesIdclasses)();
         return result;
   }   


}


