package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesTotalElements generated by hbm2java
 */
@Entity
@Table(name = "resources_total_elements")
public class ResourcesTotalElements implements java.io.Serializable {

	private ResourcesTotalElementsId id;

	public ResourcesTotalElements() {
	}

	public ResourcesTotalElements(ResourcesTotalElementsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resourcesId", column = @Column(name = "resources_id", nullable = false)), @AttributeOverride(name = "numberElements", column = @Column(name = "numberElements", nullable = false)) })
	public ResourcesTotalElementsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsId id) {
		this.id = id;
	}

}
