package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * ResourcesClassStatsId generated by hbm2java
 */
public class ResourcesClassStatsId implements java.io.Serializable {

	private long resourcesIdresources;
	private Long classesIdclasses;
	private long numberClasses;

	public ResourcesClassStatsId() {
	}

	public ResourcesClassStatsId(long resourcesIdresources, long numberClasses) {
		this.resourcesIdresources = resourcesIdresources;
		this.numberClasses = numberClasses;
	}

	public ResourcesClassStatsId(long resourcesIdresources, Long classesIdclasses, long numberClasses) {
		this.resourcesIdresources = resourcesIdresources;
		this.classesIdclasses = classesIdclasses;
		this.numberClasses = numberClasses;
	}

	public long getResourcesIdresources() {
		return this.resourcesIdresources;
	}

	public void setResourcesIdresources(long resourcesIdresources) {
		this.resourcesIdresources = resourcesIdresources;
	}

	public Long getClassesIdclasses() {
		return this.classesIdclasses;
	}

	public void setClassesIdclasses(Long classesIdclasses) {
		this.classesIdclasses = classesIdclasses;
	}

	public long getNumberClasses() {
		return this.numberClasses;
	}

	public void setNumberClasses(long numberClasses) {
		this.numberClasses = numberClasses;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesClassStatsId))
			return false;
		ResourcesClassStatsId castOther = (ResourcesClassStatsId) other;

		return (this.getResourcesIdresources() == castOther.getResourcesIdresources())
				&& ((this.getClassesIdclasses() == castOther.getClassesIdclasses()) || (this.getClassesIdclasses() != null && castOther.getClassesIdclasses() != null && this.getClassesIdclasses().equals(castOther.getClassesIdclasses())))
				&& (this.getNumberClasses() == castOther.getNumberClasses());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourcesIdresources();
		result = 37 * result + (getClassesIdclasses() == null ? 0 : this.getClassesIdclasses().hashCode());
		result = 37 * result + (int) this.getNumberClasses();
		return result;
	}

}
