package com.silicolife.anote2daemon.model.pojo;

// Generated 21/Jan/2015 14:28:04 by Hibernate Tools 4.0.0

/**
 * ResourcesContent generated by hbm2java
 */
public class ResourcesContent implements java.io.Serializable {

	private ResourcesContentId id;
	private Classes classes;
	private Resources resources;
	private Integer total;

	public ResourcesContent() {
	}

	public ResourcesContent(ResourcesContentId id, Classes classes, Resources resources) {
		this.id = id;
		this.classes = classes;
		this.resources = resources;
	}

	public ResourcesContent(ResourcesContentId id, Classes classes, Resources resources, Integer total) {
		this.id = id;
		this.classes = classes;
		this.resources = resources;
		this.total = total;
	}

	public ResourcesContentId getId() {
		return this.id;
	}

	public void setId(ResourcesContentId id) {
		this.id = id;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

}
