package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * ResourcesTotalElements generated by hbm2java
 */
public class ResourcesTotalElements implements java.io.Serializable {

	private ResourcesTotalElementsId id;

	public ResourcesTotalElements() {
	}

	public ResourcesTotalElements(ResourcesTotalElementsId id) {
		this.id = id;
	}

	public ResourcesTotalElementsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsId id) {
		this.id = id;
	}

}
