package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourcesContent generated by hbm2java
 */
@Entity
@Table(name = "resources_content")
public class ResourcesContent implements java.io.Serializable {

	private ResourcesContentId id;
	private Classes classes;
	private Resources resources;
	private Integer total;

	public ResourcesContent() {
	}

	public ResourcesContent(ResourcesContentId id, Classes classes, Resources resources) {
		this.id = id;
		this.classes = classes;
		this.resources = resources;
	}

	public ResourcesContent(ResourcesContentId id, Classes classes, Resources resources, Integer total) {
		this.id = id;
		this.classes = classes;
		this.resources = resources;
		this.total = total;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resourcesId", column = @Column(name = "resources_id", nullable = false)), @AttributeOverride(name = "classesId", column = @Column(name = "classes_id", nullable = false)) })
	public ResourcesContentId getId() {
		return this.id;
	}

	public void setId(ResourcesContentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classes_id", nullable = false, insertable = false, updatable = false)
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resources_id", nullable = false, insertable = false, updatable = false)
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "total")
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

}
