package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ResourceElements generated by hbm2java
 */
public class ResourceElements implements java.io.Serializable {

	private Long idresourceElements;
	private Resources resources;
	private Long classesIdclasses;
	private String element;
	private Integer priorety;
	private boolean active;
	private ResourcesElementsPrioreties resourcesElementsPrioreties;
	private Set<Annotations> annotationses = new HashSet<Annotations>(0);
	private Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsA = new HashSet<ResourceElementsRelation>(0);
	private Set<ResourceElementsExtenalId> resourceElementsExtenalIds = new HashSet<ResourceElementsExtenalId>(0);
	private Set<Synonyms> synonymses = new HashSet<Synonyms>(0);
	private Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsB = new HashSet<ResourceElementsRelation>(0);

	public ResourceElements() {
	}

	public ResourceElements(Resources resources, String element, boolean active) {
		this.resources = resources;
		this.element = element;
		this.active = active;
	}

	public ResourceElements(Resources resources, Long classesIdclasses, String element, Integer priorety, boolean active, ResourcesElementsPrioreties resourcesElementsPrioreties, Set<Annotations> annotationses,
			Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsA, Set<ResourceElementsExtenalId> resourceElementsExtenalIds, Set<Synonyms> synonymses, Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsB) {
		this.resources = resources;
		this.classesIdclasses = classesIdclasses;
		this.element = element;
		this.priorety = priorety;
		this.active = active;
		this.resourcesElementsPrioreties = resourcesElementsPrioreties;
		this.annotationses = annotationses;
		this.resourceElementsRelationsForIdresourceElementsA = resourceElementsRelationsForIdresourceElementsA;
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
		this.synonymses = synonymses;
		this.resourceElementsRelationsForIdresourceElementsB = resourceElementsRelationsForIdresourceElementsB;
	}

	public Long getIdresourceElements() {
		return this.idresourceElements;
	}

	public void setIdresourceElements(Long idresourceElements) {
		this.idresourceElements = idresourceElements;
	}

	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	public Long getClassesIdclasses() {
		return this.classesIdclasses;
	}

	public void setClassesIdclasses(Long classesIdclasses) {
		this.classesIdclasses = classesIdclasses;
	}

	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	public Integer getPriorety() {
		return this.priorety;
	}

	public void setPriorety(Integer priorety) {
		this.priorety = priorety;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public ResourcesElementsPrioreties getResourcesElementsPrioreties() {
		return this.resourcesElementsPrioreties;
	}

	public void setResourcesElementsPrioreties(ResourcesElementsPrioreties resourcesElementsPrioreties) {
		this.resourcesElementsPrioreties = resourcesElementsPrioreties;
	}

	public Set<Annotations> getAnnotationses() {
		return this.annotationses;
	}

	public void setAnnotationses(Set<Annotations> annotationses) {
		this.annotationses = annotationses;
	}

	public Set<ResourceElementsRelation> getResourceElementsRelationsForIdresourceElementsA() {
		return this.resourceElementsRelationsForIdresourceElementsA;
	}

	public void setResourceElementsRelationsForIdresourceElementsA(Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsA) {
		this.resourceElementsRelationsForIdresourceElementsA = resourceElementsRelationsForIdresourceElementsA;
	}

	public Set<ResourceElementsExtenalId> getResourceElementsExtenalIds() {
		return this.resourceElementsExtenalIds;
	}

	public void setResourceElementsExtenalIds(Set<ResourceElementsExtenalId> resourceElementsExtenalIds) {
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
	}

	public Set<Synonyms> getSynonymses() {
		return this.synonymses;
	}

	public void setSynonymses(Set<Synonyms> synonymses) {
		this.synonymses = synonymses;
	}

	public Set<ResourceElementsRelation> getResourceElementsRelationsForIdresourceElementsB() {
		return this.resourceElementsRelationsForIdresourceElementsB;
	}

	public void setResourceElementsRelationsForIdresourceElementsB(Set<ResourceElementsRelation> resourceElementsRelationsForIdresourceElementsB) {
		this.resourceElementsRelationsForIdresourceElementsB = resourceElementsRelationsForIdresourceElementsB;
	}

}
