package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sources generated by hbm2java
 */
@Entity
@Table(name = "sources")
public class Sources implements java.io.Serializable {

	private long id;
	private String source;
	private Set<ResourceElementsExtenalId> resourceElementsExtenalIds = new HashSet<ResourceElementsExtenalId>(0);
	private Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations = new HashSet<HypherLinkMenuSourceAssociation>(0);

	public Sources() {
	}

	public Sources(long id, String source) {
		this.id = id;
		this.source = source;
	}

	public Sources(long id, String source, Set<ResourceElementsExtenalId> resourceElementsExtenalIds, Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations) {
		this.id = id;
		this.source = source;
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
		this.hypherLinkMenuSourceAssociations = hypherLinkMenuSourceAssociations;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "source", nullable = false, length = 200)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sources")
	public Set<ResourceElementsExtenalId> getResourceElementsExtenalIds() {
		return this.resourceElementsExtenalIds;
	}

	public void setResourceElementsExtenalIds(Set<ResourceElementsExtenalId> resourceElementsExtenalIds) {
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sources")
	public Set<HypherLinkMenuSourceAssociation> getHypherLinkMenuSourceAssociations() {
		return this.hypherLinkMenuSourceAssociations;
	}

	public void setHypherLinkMenuSourceAssociations(Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations) {
		this.hypherLinkMenuSourceAssociations = hypherLinkMenuSourceAssociations;
	}

}
