package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Sources generated by hbm2java
 */
public class Sources implements java.io.Serializable {

	private Long idsources;
	private String sourceName;
	private Set<ResourceElementsExtenalId> resourceElementsExtenalIds = new HashSet<ResourceElementsExtenalId>(0);
	private Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations = new HashSet<HypherLinkMenuSourceAssociation>(0);

	public Sources() {
	}

	public Sources(String sourceName) {
		this.sourceName = sourceName;
	}

	public Sources(String sourceName, Set<ResourceElementsExtenalId> resourceElementsExtenalIds, Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations) {
		this.sourceName = sourceName;
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
		this.hypherLinkMenuSourceAssociations = hypherLinkMenuSourceAssociations;
	}

	public Long getIdsources() {
		return this.idsources;
	}

	public void setIdsources(Long idsources) {
		this.idsources = idsources;
	}

	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public Set<ResourceElementsExtenalId> getResourceElementsExtenalIds() {
		return this.resourceElementsExtenalIds;
	}

	public void setResourceElementsExtenalIds(Set<ResourceElementsExtenalId> resourceElementsExtenalIds) {
		this.resourceElementsExtenalIds = resourceElementsExtenalIds;
	}

	public Set<HypherLinkMenuSourceAssociation> getHypherLinkMenuSourceAssociations() {
		return this.hypherLinkMenuSourceAssociations;
	}

	public void setHypherLinkMenuSourceAssociations(Set<HypherLinkMenuSourceAssociation> hypherLinkMenuSourceAssociations) {
		this.hypherLinkMenuSourceAssociations = hypherLinkMenuSourceAssociations;
	}

}
