package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 15:20:27 by Hibernate Tools 4.0.0

/**
 * SynonymsId generated by hbm2java
 */
public class SynonymsId implements java.io.Serializable {

	private long resourceElementsIdresourceElements;
	private String synonym;
	private boolean active;

	public SynonymsId() {
	}

	public SynonymsId(long resourceElementsIdresourceElements, String synonym, boolean active) {
		this.resourceElementsIdresourceElements = resourceElementsIdresourceElements;
		this.synonym = synonym;
		this.active = active;
	}

	public long getResourceElementsIdresourceElements() {
		return this.resourceElementsIdresourceElements;
	}

	public void setResourceElementsIdresourceElements(long resourceElementsIdresourceElements) {
		this.resourceElementsIdresourceElements = resourceElementsIdresourceElements;
	}

	public String getSynonym() {
		return this.synonym;
	}

	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SynonymsId))
			return false;
		SynonymsId castOther = (SynonymsId) other;

		return (this.getResourceElementsIdresourceElements() == castOther.getResourceElementsIdresourceElements())
				&& ((this.getSynonym() == castOther.getSynonym()) || (this.getSynonym() != null && castOther.getSynonym() != null && this.getSynonym().equals(castOther.getSynonym()))) && (this.isActive() == castOther.isActive());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourceElementsIdresourceElements();
		result = 37 * result + (getSynonym() == null ? 0 : this.getSynonym().hashCode());
		result = 37 * result + (this.isActive() ? 1 : 0);
		return result;
	}

}
