package com.silicolife.anote2daemon.model.pojo;

// Generated 3/Fev/2015 12:37:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TypeResourcesCopy1 generated by hbm2java
 */
@Entity
@Table(name = "type_resources_copy1", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
public class TypeResourcesCopy1 implements java.io.Serializable {

	private long id;
	private String description;

	public TypeResourcesCopy1() {
	}

	public TypeResourcesCopy1(long id, String description) {
		this.id = id;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", unique = true, nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
