package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

/**
 * UsersHasDataObjectId generated by hbm2java
 */
public class UsersHasDataObjectId implements java.io.Serializable {

	private long usersId;
	private long uidResource;
	private long typeResourcesId;

	public UsersHasDataObjectId() {
	}

	public UsersHasDataObjectId(long usersId, long uidResource, long typeResourcesId) {
		this.usersId = usersId;
		this.uidResource = uidResource;
		this.typeResourcesId = typeResourcesId;
	}

	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	public long getUidResource() {
		return this.uidResource;
	}

	public void setUidResource(long uidResource) {
		this.uidResource = uidResource;
	}

	public long getTypeResourcesId() {
		return this.typeResourcesId;
	}

	public void setTypeResourcesId(long typeResourcesId) {
		this.typeResourcesId = typeResourcesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersHasDataObjectId))
			return false;
		UsersHasDataObjectId castOther = (UsersHasDataObjectId) other;

		return (this.getUsersId() == castOther.getUsersId()) && (this.getUidResource() == castOther.getUidResource()) && (this.getTypeResourcesId() == castOther.getTypeResourcesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsersId();
		result = 37 * result + (int) this.getUidResource();
		result = 37 * result + (int) this.getTypeResourcesId();
		return result;
	}

}
