package com.silicolife.anote2daemon.model.pojo;

// Generated 16/Jan/2015 16:00:05 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable {

	private long version;
	private Date date;
	private String comments;

	public Version() {
	}

	public Version(long version, Date date) {
		this.version = version;
		this.date = date;
	}

	public Version(long version, Date date, String comments) {
		this.version = version;
		this.date = date;
		this.comments = comments;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
