package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorpusProperties generated by hbm2java
 */
@Entity
@Table(name = "corpus_properties")
public class CorpusProperties implements java.io.Serializable {

	private CorpusPropertiesId id;
	private Corpus corpus;
	private String propValue;

	public CorpusProperties() {
	}

	public CorpusProperties(CorpusPropertiesId id, Corpus corpus, String propValue) {
		this.id = id;
		this.corpus = corpus;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "corpusId", column = @Column(name = "corpus_id", nullable = false)), @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false, length = 250)) })
	public CorpusPropertiesId getId() {
		return this.id;
	}

	public void setId(CorpusPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corpus_id", nullable = false, insertable = false, updatable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@Column(name = "prop_value", nullable = false)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
