package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusHasPublicationsId generated by hbm2java
 */
@Embeddable
public class CorpusHasPublicationsId implements java.io.Serializable {

	private long corpusId;
	private long publicationsId;

	public CorpusHasPublicationsId() {
	}

	public CorpusHasPublicationsId(long corpusId, long publicationsId) {
		this.corpusId = corpusId;
		this.publicationsId = publicationsId;
	}

	@Column(name = "corpus_id", nullable = false)
	public long getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(long corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "publications_id", nullable = false)
	public long getPublicationsId() {
		return this.publicationsId;
	}

	public void setPublicationsId(long publicationsId) {
		this.publicationsId = publicationsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusHasPublicationsId))
			return false;
		CorpusHasPublicationsId castOther = (CorpusHasPublicationsId) other;

		return (this.getCorpusId() == castOther.getCorpusId()) && (this.getPublicationsId() == castOther.getPublicationsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCorpusId();
		result = 37 * result + (int) this.getPublicationsId();
		return result;
	}

}
