package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PublicationsHasPublicationLabels generated by hbm2java
 */
@Entity
@Table(name = "publications_has_publication_labels")
public class PublicationsHasPublicationLabels implements java.io.Serializable {

	private PublicationsHasPublicationLabelsId id;
	private PublicationsLabels publicationsLabels;
	private Publications publications;

	public PublicationsHasPublicationLabels() {
	}

	public PublicationsHasPublicationLabels(PublicationsHasPublicationLabelsId id, PublicationsLabels publicationsLabels, Publications publications) {
		this.id = id;
		this.publicationsLabels = publicationsLabels;
		this.publications = publications;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "publicationsId", column = @Column(name = "publications_id", nullable = false)), @AttributeOverride(name = "publicationLabelsId", column = @Column(name = "publication_labels_id", nullable = false)) })
	public PublicationsHasPublicationLabelsId getId() {
		return this.id;
	}

	public void setId(PublicationsHasPublicationLabelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_labels_id", nullable = false, insertable = false, updatable = false)
	public PublicationsLabels getPublicationsLabels() {
		return this.publicationsLabels;
	}

	public void setPublicationsLabels(PublicationsLabels publicationsLabels) {
		this.publicationsLabels = publicationsLabels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publications_id", nullable = false, insertable = false, updatable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

}
