package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicationsQueryRelevanceId generated by hbm2java
 */
@Embeddable
public class PublicationsQueryRelevanceId implements java.io.Serializable {

	private long publicationsId;
	private long queriesId;

	public PublicationsQueryRelevanceId() {
	}

	public PublicationsQueryRelevanceId(long publicationsId, long queriesId) {
		this.publicationsId = publicationsId;
		this.queriesId = queriesId;
	}

	@Column(name = "publications_id", nullable = false)
	public long getPublicationsId() {
		return this.publicationsId;
	}

	public void setPublicationsId(long publicationsId) {
		this.publicationsId = publicationsId;
	}

	@Column(name = "queries_id", nullable = false)
	public long getQueriesId() {
		return this.queriesId;
	}

	public void setQueriesId(long queriesId) {
		this.queriesId = queriesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicationsQueryRelevanceId))
			return false;
		PublicationsQueryRelevanceId castOther = (PublicationsQueryRelevanceId) other;

		return (this.getPublicationsId() == castOther.getPublicationsId()) && (this.getQueriesId() == castOther.getQueriesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPublicationsId();
		result = 37 * result + (int) this.getQueriesId();
		return result;
	}

}
