package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PublicationsLabels generated by hbm2java
 */
@Entity
@Table(name = "publications_labels", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
public class PublicationsLabels implements java.io.Serializable {

	private long id;
	private String description;
	private Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses = new HashSet<PublicationsHasPublicationLabels>(0);

	public PublicationsLabels() {
	}

	public PublicationsLabels(long id, String description) {
		this.id = id;
		this.description = description;
	}

	public PublicationsLabels(long id, String description, Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses) {
		this.id = id;
		this.description = description;
		this.publicationsHasPublicationLabelses = publicationsHasPublicationLabelses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", unique = true, nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicationsLabels")
	public Set<PublicationsHasPublicationLabels> getPublicationsHasPublicationLabelses() {
		return this.publicationsHasPublicationLabelses;
	}

	public void setPublicationsHasPublicationLabelses(Set<PublicationsHasPublicationLabels> publicationsHasPublicationLabelses) {
		this.publicationsHasPublicationLabelses = publicationsHasPublicationLabelses;
	}

}
