package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * QueriesType generated by hbm2java
 */
@Entity
@Table(name = "queries_type", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
public class QueriesType implements java.io.Serializable {

	private long id;
	private String description;
	private Set<Queries> querieses = new HashSet<Queries>(0);

	public QueriesType() {
	}

	public QueriesType(long id) {
		this.id = id;
	}

	public QueriesType(long id, String description, Set<Queries> querieses) {
		this.id = id;
		this.description = description;
		this.querieses = querieses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", unique = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queriesType")
	public Set<Queries> getQuerieses() {
		return this.querieses;
	}

	public void setQuerieses(Set<Queries> querieses) {
		this.querieses = querieses;
	}

}
