package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QueriesProperties generated by hbm2java
 */
@Entity
@Table(name = "queries_properties")
public class QueriesProperties implements java.io.Serializable {

	private QueriesPropertiesId id;
	private Queries queries;
	private String propValue;

	public QueriesProperties() {
	}

	public QueriesProperties(QueriesPropertiesId id, Queries queries, String propValue) {
		this.id = id;
		this.queries = queries;
		this.propValue = propValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "queriesId", column = @Column(name = "queries_id", nullable = false)), @AttributeOverride(name = "propKey", column = @Column(name = "prop_key", nullable = false, length = 250)) })
	public QueriesPropertiesId getId() {
		return this.id;
	}

	public void setId(QueriesPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "queries_id", nullable = false, insertable = false, updatable = false)
	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	@Column(name = "prop_value", nullable = false, length = 250)
	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

}
