package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResourcesType generated by hbm2java
 */
@Entity
@Table(name = "resources_type", uniqueConstraints = @UniqueConstraint(columnNames = "resource_type"))
public class ResourcesType implements java.io.Serializable {

	private long id;
	private String resourceType;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public ResourcesType() {
	}

	public ResourcesType(long id, String resourceType) {
		this.id = id;
		this.resourceType = resourceType;
	}

	public ResourcesType(long id, String resourceType, Set<Resources> resourceses) {
		this.id = id;
		this.resourceType = resourceType;
		this.resourceses = resourceses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "resource_type", unique = true, nullable = false, length = 250)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourcesType")
	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
