package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGroupsHasUsersAccessLevels generated by hbm2java
 */
@Entity
@Table(name = "users_groups_has_users_access_levels")
public class UsersGroupsHasUsersAccessLevels implements java.io.Serializable {

	private UsersGroupsHasUsersAccessLevelsId id;
	private UsersGroups usersGroups;
	private UsersAccessLevels usersAccessLevels;

	public UsersGroupsHasUsersAccessLevels() {
	}

	public UsersGroupsHasUsersAccessLevels(UsersGroupsHasUsersAccessLevelsId id, UsersGroups usersGroups, UsersAccessLevels usersAccessLevels) {
		this.id = id;
		this.usersGroups = usersGroups;
		this.usersAccessLevels = usersAccessLevels;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "groupsId", column = @Column(name = "groups_id", nullable = false)), @AttributeOverride(name = "accessLevelsId", column = @Column(name = "access_levels_id", nullable = false)) })
	public UsersGroupsHasUsersAccessLevelsId getId() {
		return this.id;
	}

	public void setId(UsersGroupsHasUsersAccessLevelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groups_id", nullable = false, insertable = false, updatable = false)
	public UsersGroups getUsersGroups() {
		return this.usersGroups;
	}

	public void setUsersGroups(UsersGroups usersGroups) {
		this.usersGroups = usersGroups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "access_levels_id", nullable = false, insertable = false, updatable = false)
	public UsersAccessLevels getUsersAccessLevels() {
		return this.usersAccessLevels;
	}

	public void setUsersAccessLevels(UsersAccessLevels usersAccessLevels) {
		this.usersAccessLevels = usersAccessLevels;
	}

}
