package com.silicolife.anote2daemon.model.core.entities;

// Generated 5/Fev/2015 14:40:20 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "version")
public class Version implements java.io.Serializable {

	private long version;
	private Date versionDate;
	private String notes;

	public Version() {
	}

	public Version(long version, Date versionDate) {
		this.version = version;
		this.versionDate = versionDate;
	}

	public Version(long version, Date versionDate, String notes) {
		this.version = version;
		this.versionDate = versionDate;
		this.notes = notes;
	}

	@Id
	@Column(name = "version", unique = true, nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "version_date", nullable = false, length = 10)
	public Date getVersionDate() {
		return this.versionDate;
	}

	public void setVersionDate(Date versionDate) {
		this.versionDate = versionDate;
	}

	@Column(name = "notes", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
